import re
from collections import defaultdict
import itertools

def porter_stem(word):
    word = word.lower()

    # Step 1a
    if word.endswith("sses"):
        word = word[:-2]
    elif word.endswith("ies"):
        word = word[:-2]
    elif word.endswith("ss"):
        pass
    elif word.endswith("s"):
        word = word[:-1]

    # Step 1b
    if word.endswith("eed"):
        if measure(word[:-3]) > 0:
            word = word[:-1]
    elif word.endswith("ed"):
        stem = word[:-2]
        if contains_vowel(stem):
            word = stem
            word = step1b_helper(word)
    elif word.endswith("ing"):
        stem = word[:-3]
        if contains_vowel(stem):
            word = stem
            word = step1b_helper(word)

    return word

def step1b_helper(word):
    if word.endswith(("at", "bl", "iz")):
        word += "e"
    elif ends_with_double_consonant(word):
        if word[-1] not in "lsz":
            word = word[:-1]
    elif measure(word) == 1 and cvc(word):
        word += "e"
    return word

def contains_vowel(word):
    return any(c in "aeiou" for c in word)

def ends_with_double_consonant(word):
    return len(word) > 1 and word[-1] == word[-2] and word[-1] not in "aeiou"

def consonant(ch):
    return ch not in "aeiou"

def cvc(word):
    if len(word) < 3:
        return False
    c, v, c2 = word[-3], word[-2], word[-1]
    return consonant(c) and not consonant(v) and consonant(c2) and c2 not in "wxy"

def measure(word):
    form = ""
    for ch in word:
        form += "C" if consonant(ch) else "V"
    form = re.sub(r"C+", "C", form)
    form = re.sub(r"V+", "V", form)
    return form.count("VC")


semantic_classes = [
    { 'abandoned', 'abandonment' },
{ 'abc' },
{ 'aberration' },
{ 'ability' },
{ 'able' },
{ 'aboard' },
{ 'abolish', 'abolishing' },
{ 'abort', 'abortion' },
{ 'abound' },
{ 'about' },
{ 'above' },
{ 'abraham' },
{ 'abrego' },
{ 'abroad' },
{ 'abrupt' },
{ 'absence' },
{ 'absolute' },
{ 'absorb', 'absorbing', 'absorbs' },
{ 'absurdity' },
{ 'abuse' },
{ 'academic', 'academics' },
{ 'academies', 'academy' },
{ 'academia' },
{ 'accept', 'acceptable', 'acceptance', 'accepted' },
{ 'access', 'accessible' },
{ 'accident', 'accidents' },
{ 'accidentally' },
{ 'accommodating' },
{ 'accomplish', 'accomplished' },
{ 'according' },
{ 'account', 'accountability', 'accounting', 'accounts' },
{ 'accurate' },
{ 'accuracy' },
{ 'accuse', 'accused', 'accuses' },
{ 'acetylsalicylic' },
{ 'achieve', 'achieved', 'achievement' },
{ 'acid' },
{ 'acknowledged', 'acknowledges' },
{ 'acolytes' },
{ 'acquiesced' },
{ 'acquire', 'acquired' },
{ 'across' },
{ 'act', 'acted', 'acting', 'acts' },
{ 'action', 'actions' },
{ 'activation', 'active', 'actively', 'activism', 'activities', 'activity' },
{ 'activist', 'activists' },
{ 'actor', 'actors' },
{ 'actually' },
{ 'acutely' },
{ 'added', 'adding' },
{ 'adage' },
{ 'adaptation' },
{ 'add', 'adds' },
{ 'addition', 'additional', 'additions', 'additives' },
{ 'address' },
{ 'adefunke' },
{ 'adeyemi' },
{ 'adherence' },
{ 'adjudication' },
{ 'adjunct' },
{ 'admin' },
{ 'administering' },
{ 'administration', 'administrative', 'administrator' },
{ 'admirable', 'admire' },
{ 'admission', 'admissions' },
{ 'admit', 'admitted', 'admitting' },
{ 'adolescents' },
{ 'adorable' },
{ 'adult', 'adults' },
{ 'advance', 'advanced', 'advances', 'advancing' },
{ 'advantage' },
{ 'adverts' },
{ 'advised', 'adviser' },
{ 'advisory' },
{ 'advocate', 'advocated', 'advocates', 'advocating' },
{ 'aesthetic', 'aesthetical' },
{ 'affair', 'affairs' },
{ 'affect', 'affected', 'affection' },
{ 'affirmative' },
{ 'afghanistan' },
{ 'afraid' },
{ 'africa' },
{ 'african' },
{ 'afros' },
{ 'after' },
{ 'afterthought' },
{ 'afterwards' },
{ 'ag' },
{ 'again' },
{ 'against' },
{ 'age', 'aged', 'ages' },
{ 'agencies', 'agency' },
{ 'agenda', 'agendas' },
{ 'agent', 'agents' },
{ 'aggressive', 'aggressively' },
{ 'ago' },
{ 'agree', 'agreed', 'agrees' },
{ 'agreements' },
{ 'ahead' },
{ 'ai' },
{ 'aid', 'aids' },
{ 'ails' },
{ 'aimed', 'aims' },
{ 'air', 'aired' },
{ 'airborne' },
{ 'airwaves' },
{ 'aisles' },
{ 'akin' },
{ 'alabosi' },
{ 'alan' },
{ 'alarming' },
{ 'albeit' },
{ 'alberta' },
{ 'albertus' },
{ 'alcohol', 'alcoholic' },
{ 'alee' },
{ 'alert' },
{ 'alexander' },
{ 'algorithm', 'algorithms' },
{ 'alien', 'alienated', 'alienates', 'alienation' },
{ 'aligned', 'alignment' },
{ 'alito' },
{ 'alive' },
{ 'all' },
{ 'allegations' },
{ 'allegiances' },
{ 'allied', 'allies' },
{ 'alliance', 'alliances' },
{ 'allow', 'allowed', 'allowing' },
{ 'almost' },
{ 'almroth' },
{ 'alone' },
{ 'along' },
{ 'alongside' },
{ 'already' },
{ 'alsatian' },
{ 'also' },
{ 'alternative', 'alternatives' },
{ 'although' },
{ 'altogether' },
{ 'aluminium' },
{ 'alumni' },
{ 'always' },
{ 'am' },
{ 'amateur' },
{ 'amazing' },
{ 'amazingly' },
{ 'ambition' },
{ 'ambongo' },
{ 'ambushed' },
{ 'amend' },
{ 'america' },
{ 'american', 'americans' },
{ 'amid' },
{ 'amine' },
{ 'amiss' },
{ 'among' },
{ 'amount' },
{ 'amplified', 'amplify' },
{ 'analysis' },
{ 'analyst', 'analysts' },
{ 'analyzed' },
{ 'anchor' },
{ 'ancient' },
{ 'andrew' },
{ 'angelo' },
{ 'anger' },
{ 'angry' },
{ 'anguish' },
{ 'any' },
{ 'animal', 'animals', 'anime' },
{ 'anne' },
{ 'annihilation' },
{ 'announced', 'announcement', 'announcements' },
{ 'annoyed' },
{ 'annual', 'annually' },
{ 'anonymity', 'anonymous', 'anonymously' },
{ 'another' },
{ 'answer', 'answering', 'answers' },
{ 'antagonism' },
{ 'anteri' },
{ 'anthropologist' },
{ 'anthropomorphised' },
{ 'antibacterial' },
{ 'antibiotic' },
{ 'antiretroviral' },
{ 'antisemitism' },
{ 'antisepsis' },
{ 'antiseptic', 'antiseptics' },
{ 'antiviral' },
{ 'antonio' },
{ 'antónio' },
{ 'anxieties', 'anxiety' },
{ 'anymore' },
{ 'anyone' },
{ 'anything' },
{ 'anyway' },
{ 'apartment', 'apartments' },
{ 'apartheid' },
{ 'apologizing', 'apology' },
{ 'apologetic' },
{ 'apologised' },
{ 'app', 'apps' },
{ 'appalling' },
{ 'apparent', 'apparently' },
{ 'appeal', 'appeals' },
{ 'appear', 'appearance', 'appearing', 'appears' },
{ 'appease', 'appeasement' },
{ 'appiah' },
{ 'apple' },
{ 'applied', 'apply' },
{ 'appliances' },
{ 'applications' },
{ 'appoint', 'appointed', 'appointing', 'appointments' },
{ 'appointee' },
{ 'apprenticeships' },
{ 'approach', 'approached', 'approaches' },
{ 'appropriately' },
{ 'approval', 'approve', 'approved' },
{ 'approximately' },
{ 'apr' },
{ 'april' },
{ 'arab' },
{ 'arabia' },
{ 'arc' },
{ 'archbishop' },
{ 'archetypal' },
{ 'archive' },
{ 'area', 'areas' },
{ 'aren' },
{ 'arenas' },
{ 'argue', 'argued', 'argues', 'arguing' },
{ 'arguably' },
{ 'argument', 'arguments' },
{ 'arkansas' },
{ 'armed' },
{ 'army' },
{ 'around' },
{ 'arrangements' },
{ 'array' },
{ 'arrest', 'arrested' },
{ 'arrival', 'arrive', 'arrived' },
{ 'arrogant' },
{ 'arts' },
{ 'arthur' },
{ 'article', 'articles' },
{ 'artificial' },
{ 'artistic' },
{ 'asap' },
{ 'asia' },
{ 'asian' },
{ 'aside' },
{ 'ask', 'asked', 'asking' },
{ 'aspects' },
{ 'aspiration', 'aspirations', 'aspire' },
{ 'aspirin' },
{ 'assault' },
{ 'assembled', 'assembly' },
{ 'assert', 'asserting', 'assertion' },
{ 'assessed', 'assessment', 'assessments' },
{ 'assistant' },
{ 'associated', 'association', 'associations' },
{ 'assumption' },
{ 'assurance', 'assured' },
{ 'astor' },
{ 'ate' },
{ 'athens' },
{ 'atlantic' },
{ 'attack', 'attacked', 'attacking', 'attacks' },
{ 'attempt', 'attempts' },
{ 'attend', 'attendant', 'attended', 'attending' },
{ 'attendees' },
{ 'attention' },
{ 'attest' },
{ 'attitude', 'attitudes' },
{ 'attorney' },
{ 'attract' },
{ 'attributes' },
{ 'audacity' },
{ 'audience' },
{ 'audit', 'audits' },
{ 'australia' },
{ 'australian' },
{ 'austrian' },
{ 'authentically', 'authentication', 'authenticity' },
{ 'author', 'authored', 'authorities', 'authority', 'authors' },
{ 'autism' },
{ 'autistic' },
{ 'auto' },
{ 'autocracies', 'autocracy' },
{ 'autocratic', 'autocrats' },
{ 'automatically' },
{ 'autonomy' },
{ 'autumn' },
{ 'available' },
{ 'average' },
{ 'avi' },
{ 'avlon' },
{ 'avoid', 'avoiding' },
{ 'awful' },
{ 'awaiting' },
{ 'awakenings' },
{ 'aware' },
{ 'awash' },
{ 'away' },
{ 'axis' },
{ 'ayoub' },
{ 'ayrshire' },
{ 'azt' },
{ 'b' },
{ 'baby' },
{ 'back', 'backs' },
{ 'backbiting' },
{ 'backbreaking' },
{ 'backdrop' },
{ 'backfired' },
{ 'backfoot' },
{ 'background', 'backgrounds' },
{ 'backlash' },
{ 'backpack' },
{ 'backstory' },
{ 'backwards' },
{ 'bacterial' },
{ 'bacteria' },
{ 'bacteriologist' },
{ 'bad' },
{ 'badar' },
{ 'badenoch' },
{ 'badge' },
{ 'badly' },
{ 'baffled' },
{ 'bafflement' },
{ 'bag' },
{ 'bailiff' },
{ 'baked' },
{ 'balance', 'balances' },
{ 'balkanised' },
{ 'balls' },
{ 'balm' },
{ 'ban', 'banned' },
{ 'banal', 'banality' },
{ 'band' },
{ 'bandwagon' },
{ 'bank', 'banking' },
{ 'banner' },
{ 'bannon' },
{ 'banting' },
{ 'baptised' },
{ 'bar' },
{ 'barcode' },
{ 'bards' },
{ 'barely' },
{ 'bargain' },
{ 'barley' },
{ 'barrage', 'barrages' },
{ 'barrel' },
{ 'barringer' },
{ 'base', 'based', 'bases' },
{ 'baseball' },
{ 'bash' },
{ 'basis' },
{ 'basic' },
{ 'bastions' },
{ 'bathroom' },
{ 'battered' },
{ 'battle' },
{ 'battlefield' },
{ 'bayer' },
{ 'bbc' },
{ 'bds' },
{ 'beings' },
{ 'beacon' },
{ 'bears' },
{ 'beast' },
{ 'beaten' },
{ 'beautiful' },
{ 'became' },
{ 'because' },
{ 'become', 'becomes', 'becoming' },
{ 'bed' },
{ 'bedside' },
{ 'before' },
{ 'begging' },
{ 'began' },
{ 'begin', 'beginning', 'begins' },
{ 'begun' },
{ 'behaviors' },
{ 'behind' },
{ 'behr' },
{ 'beijing' },
{ 'belief', 'beliefs' },
{ 'believable', 'believe', 'believed', 'believes' },
{ 'belong', 'belonging' },
{ 'below' },
{ 'ben' },
{ 'bench' },
{ 'benedict' },
{ 'beneficial' },
{ 'beneficiary' },
{ 'benefit', 'benefits' },
{ 'berita' },
{ 'berries', 'berry' },
{ 'best' },
{ 'besungu' },
{ 'bet', 'betting' },
{ 'beta' },
{ 'beth' },
{ 'better' },
{ 'between' },
{ 'beverages' },
{ 'beyond' },
{ 'bias' },
{ 'bianca' },
{ 'biased', 'biases' },
{ 'biden' },
{ 'big' },
{ 'bigger' },
{ 'biggest' },
{ 'bigotries' },
{ 'bill', 'bills' },
{ 'billion', 'billions' },
{ 'biochemist' },
{ 'biodiversity' },
{ 'biologically' },
{ 'biosciences' },
{ 'birth', 'births' },
{ 'bishops' },
{ 'bit', 'bits' },
{ 'bizarre' },
{ 'black' },
{ 'blackmailing' },
{ 'blame' },
{ 'blanket' },
{ 'bleach' },
{ 'bleak' },
{ 'blessings' },
{ 'blizzard' },
{ 'blocked' },
{ 'blond' },
{ 'blood' },
{ 'bloodstream' },
{ 'blossom' },
{ 'blue' },
{ 'blueprint' },
{ 'blunted' },
{ 'blurring', 'blurs' },
{ 'bo' },
{ 'boarding' },
{ 'boasberg' },
{ 'bob' },
{ 'body' },
{ 'boer' },
{ 'bohemia' },
{ 'boiling', 'boils' },
{ 'boilers' },
{ 'bold' },
{ 'bolsonaro' },
{ 'bolster', 'bolstering' },
{ 'bolt' },
{ 'bomb' },
{ 'bombast' },
{ 'bona' },
{ 'bondi' },
{ 'book', 'books' },
{ 'bookmakers' },
{ 'booming' },
{ 'boost', 'boosting', 'boosts' },
{ 'borchgrevink' },
{ 'border', 'borders' },
{ 'boring' },
{ 'boris' },
{ 'born' },
{ 'borrowing' },
{ 'boss' },
{ 'boston' },
{ 'botched' },
{ 'both' },
{ 'bottle' },
{ 'bottom' },
{ 'boulogne' },
{ 'bounds' },
{ 'boundaries' },
{ 'bowl' },
{ 'box' },
{ 'boxers' },
{ 'boys' },
{ 'boycotting' },
{ 'boycott', 'boycotts' },
{ 'braced' },
{ 'brain' },
{ 'bran' },
{ 'branch', 'branches' },
{ 'brand', 'branded', 'brands' },
{ 'brandon' },
{ 'brayman' },
{ 'brazil' },
{ 'breads' },
{ 'break' },
{ 'breakfast' },
{ 'breakthrough' },
{ 'breath' },
{ 'breed' },
{ 'brevity' },
{ 'brexit' },
{ 'brief' },
{ 'briefly' },
{ 'brightest' },
{ 'brilliant' },
{ 'bring', 'bringing', 'brings' },
{ 'brink' },
{ 'britain' },
{ 'british' },
{ 'broad' },
{ 'broader' },
{ 'broadly' },
{ 'broders' },
{ 'broken' },
{ 'brooks' },
{ 'brought' },
{ 'bruised' },
{ 'brutal' },
{ 'bst' },
{ 'bubble', 'bubbles', 'bubbling' },
{ 'bucket' },
{ 'budapest' },
{ 'budget', 'budgets' },
{ 'build', 'building', 'builds' },
{ 'bullet' },
{ 'bullied', 'bullying' },
{ 'bureaucratic' },
{ 'burgum' },
{ 'burlap' },
{ 'burn' },
{ 'burrowed' },
{ 'burst' },
{ 'bush' },
{ 'business', 'businesses' },
{ 'buy', 'buying' },
{ 'buyers' },
{ 'byelection' },
{ 'bygone' },
{ 'bypassing' },
{ 'byword' },
{ 'c' },
{ 'ca' },
{ 'cabin' },
{ 'cabinet' },
{ 'caccialanza' },
{ 'cachet' },
{ 'caesarean' },
{ 'cages' },
{ 'calcium' },
{ 'calculated' },
{ 'caledonia' },
{ 'california' },
{ 'call', 'called', 'calling', 'calls' },
{ 'callow' },
{ 'calm' },
{ 'calorie', 'calories' },
{ 'came' },
{ 'campaign', 'campaigning', 'campaigns' },
{ 'campus' },
{ 'campuses' },
{ 'canada' },
{ 'canadian', 'canadians' },
{ 'cancel', 'canceled', 'cancellations', 'cancelled' },
{ 'cancer' },
{ 'candidate', 'candidates' },
{ 'capable' },
{ 'capacity' },
{ 'capital', 'capitalize' },
{ 'captions' },
{ 'captivity' },
{ 'captured', 'capturing' },
{ 'car', 'cars' },
{ 'carbohydrate', 'carbohydrates' },
{ 'carbolic' },
{ 'carbon' },
{ 'card' },
{ 'cardinal', 'cardinals' },
{ 'cardiovascular' },
{ 'care', 'careful', 'carefully' },
{ 'career', 'careers' },
{ 'caricature' },
{ 'carnage' },
{ 'carolina' },
{ 'carried', 'carry', 'carrying' },
{ 'cartoonish' },
{ 'carving' },
{ 'case', 'cases' },
{ 'cash' },
{ 'cassidy' },
{ 'cast', 'casting' },
{ 'casual' },
{ 'cats' },
{ 'catalyst' },
{ 'catch' },
{ 'catechism' },
{ 'categorize' },
{ 'categories' },
{ 'cater' },
{ 'catherine' },
{ 'catholic', 'catholics' },
{ 'caught' },
{ 'cause', 'caused', 'causes', 'causing' },
{ 'cautioned' },
{ 'cautionary' },
{ 'cautious' },
{ 'cavalier' },
{ 'caving' },
{ 'celebrate', 'celebrated', 'celebrates', 'celebration', 'celebrities' },
{ 'celibacy' },
{ 'cells' },
{ 'center', 'centers' },
{ 'centerpiece' },
{ 'centres' },
{ 'central' },
{ 'centuries', 'century' },
{ 'ceo' },
{ 'cereal', 'cereals' },
{ 'ceremony' },
{ 'certain' },
{ 'certainly' },
{ 'certificate', 'certification' },
{ 'chain', 'chains' },
{ 'chair' },
{ 'chairman' },
{ 'chalice' },
{ 'challenge', 'challenged', 'challenges', 'challenging' },
{ 'chamber' },
{ 'champagne' },
{ 'chan' },
{ 'chance', 'chances' },
{ 'chancellor' },
{ 'change', 'changed', 'changes', 'changing' },
{ 'channel', 'channels' },
{ 'chant' },
{ 'chaos' },
{ 'chapel' },
{ 'chapter' },
{ 'character' },
{ 'characterization' },
{ 'characterisations' },
{ 'characteristics' },
{ 'charged', 'charges', 'charging' },
{ 'charismatic' },
{ 'charitable' },
{ 'charities', 'charity' },
{ 'charles' },
{ 'chased', 'chasing' },
{ 'chastising' },
{ 'chat', 'chats' },
{ 'cheaper' },
{ 'check', 'checking', 'checks' },
{ 'cheetos' },
{ 'chelation' },
{ 'chemical', 'chemicals' },
{ 'chemist' },
{ 'cherished' },
{ 'cherry' },
{ 'chetha' },
{ 'cheviot' },
{ 'chief' },
{ 'child' },
{ 'children' },
{ 'chilling' },
{ 'chimes' },
{ 'china' },
{ 'chinese' },
{ 'chips' },
{ 'chlorpromazine' },
{ 'chocolate' },
{ 'choice', 'choices' },
{ 'cholesterol' },
{ 'choose', 'chooses', 'choosing' },
{ 'chose' },
{ 'chosen' },
{ 'chris' },
{ 'christ' },
{ 'christendom' },
{ 'christian', 'christianity', 'christians' },
{ 'christiansen' },
{ 'chronic' },
{ 'chronologically', 'chronologies' },
{ 'church', 'churches' },
{ 'circle', 'circles', 'circling' },
{ 'circus' },
{ 'circuit' },
{ 'circulated', 'circulating' },
{ 'circumstances' },
{ 'cited' },
{ 'cities', 'city' },
{ 'citizen', 'citizens' },
{ 'citizenship' },
{ 'civil' },
{ 'civilian', 'civilians' },
{ 'clad' },
{ 'claim', 'claimed', 'claiming', 'claims' },
{ 'clarence' },
{ 'clarification' },
{ 'clarifying' },
{ 'clarity' },
{ 'clash' },
{ 'classes' },
{ 'classy' },
{ 'classified' },
{ 'classrooms' },
{ 'clean' },
{ 'cleaner' },
{ 'clear', 'cleared' },
{ 'clearer' },
{ 'clearest' },
{ 'clearly' },
{ 'cleric' },
{ 'clerk' },
{ 'clients' },
{ 'climate' },
{ 'climbdown' },
{ 'clinging' },
{ 'clinical' },
{ 'clint' },
{ 'clock' },
{ 'cloistered' },
{ 'clone', 'cloned' },
{ 'close', 'closed', 'closely' },
{ 'closer' },
{ 'closest' },
{ 'clothed', 'clothes' },
{ 'clouded' },
{ 'cnn' },
{ 'coalition' },
{ 'coddling' },
{ 'code', 'codes' },
{ 'coel' },
{ 'coerce' },
{ 'coercive' },
{ 'coexistence' },
{ 'cognition' },
{ 'coherent' },
{ 'cohesive' },
{ 'coincidentally' },
{ 'cola' },
{ 'cold' },
{ 'collaboration' },
{ 'colleague', 'colleagues' },
{ 'collect', 'collection', 'collective', 'collectively' },
{ 'college', 'colleges' },
{ 'collide', 'collided', 'colliding' },
{ 'collinson' },
{ 'collision', 'collisions' },
{ 'colonize' },
{ 'colonial', 'colonialism', 'colonies' },
{ 'colossal' },
{ 'colourants', 'colourful', 'colours' },
{ 'columbia' },
{ 'column' },
{ 'columnist' },
{ 'combat', 'combating' },
{ 'combination', 'combine', 'combines' },
{ 'combinatorics' },
{ 'come', 'comely', 'comes', 'coming' },
{ 'comforting' },
{ 'commanding' },
{ 'comment', 'commentators', 'comments' },
{ 'commission' },
{ 'commissioners' },
{ 'commitment', 'commitments', 'committed' },
{ 'common' },
{ 'commonly' },
{ 'communication', 'communism', 'community' },
{ 'communist' },
{ 'compact' },
{ 'companies', 'company' },
{ 'compared' },
{ 'comparison' },
{ 'compassion' },
{ 'compassionate' },
{ 'compelling' },
{ 'competing' },
{ 'complain', 'complaining' },
{ 'complete', 'completely', 'completing' },
{ 'complex' },
{ 'complexion' },
{ 'comply' },
{ 'complicated' },
{ 'component', 'components' },
{ 'compound', 'compounded', 'compounds' },
{ 'compromise' },
{ 'computer' },
{ 'conakry' },
{ 'concentrate', 'concentrating' },
{ 'conception' },
{ 'concern', 'concerned', 'concerns' },
{ 'concessions' },
{ 'conclave', 'conclaves' },
{ 'conclusion', 'conclusively' },
{ 'concocted' },
{ 'concrete' },
{ 'condemn' },
{ 'conditions' },
{ 'conduct', 'conducted' },
{ 'confer', 'conference', 'conferences', 'conferred', 'conferring' },
{ 'confidence', 'confident' },
{ 'confidential' },
{ 'confined' },
{ 'confirm', 'confirmation', 'confirmed', 'confirms' },
{ 'conflict', 'conflicting', 'conflicts' },
{ 'confront' },
{ 'confused' },
{ 'congestion' },
{ 'congo' },
{ 'congolese' },
{ 'connect', 'connected' },
{ 'connecticut' },
{ 'conquest' },
{ 'conscience' },
{ 'consciousness' },
{ 'conscriptions' },
{ 'consensus' },
{ 'consequences', 'consequently' },
{ 'consequential' },
{ 'conservation', 'conservative', 'conservatives', 'conserving' },
{ 'consider', 'considered', 'considering' },
{ 'considerable', 'considerably', 'consideration', 'considerations' },
{ 'consoles' },
{ 'conspiracy' },
{ 'constant' },
{ 'constantly' },
{ 'constituents' },
{ 'constitutes', 'constitutional' },
{ 'constrain', 'constrained' },
{ 'constraints' },
{ 'constructive' },
{ 'consume', 'consumed', 'consumer', 'consumers' },
{ 'consumption' },
{ 'contact', 'contacted' },
{ 'contagion' },
{ 'contain', 'containing', 'contains' },
{ 'contaminant', 'contaminated' },
{ 'contemporary' },
{ 'contempt' },
{ 'content' },
{ 'contest' },
{ 'context' },
{ 'continent' },
{ 'continually', 'continue', 'continued', 'continues' },
{ 'contraception' },
{ 'contract', 'contracted', 'contracting' },
{ 'contradict', 'contradictions' },
{ 'contradictory' },
{ 'contrary' },
{ 'contribution', 'contributions' },
{ 'control', 'controlled' },
{ 'controversial', 'controversy' },
{ 'conundrums' },
{ 'conventional' },
{ 'converged' },
{ 'conversational', 'conversations' },
{ 'convictions' },
{ 'convince', 'convinced' },
{ 'cooked' },
{ 'copenhagen' },
{ 'copycat' },
{ 'copyright' },
{ 'core' },
{ 'corks' },
{ 'corn' },
{ 'cornerstone' },
{ 'corporation' },
{ 'corpuscles' },
{ 'correct' },
{ 'correspondents' },
{ 'cost', 'costs' },
{ 'couch' },
{ 'cough' },
{ 'couldn' },
{ 'council' },
{ 'counsel' },
{ 'counted', 'counts' },
{ 'counter' },
{ 'counterpoint' },
{ 'countervailed' },
{ 'countless' },
{ 'countries', 'country' },
{ 'couple' },
{ 'course' },
{ 'court', 'courts' },
{ 'courthouses' },
{ 'cover', 'covering' },
{ 'coverage' },
{ 'crack' },
{ 'crackdown' },
{ 'cradle' },
{ 'crank' },
{ 'crashing' },
{ 'crave', 'craved' },
{ 'crazy' },
{ 'cream' },
{ 'create', 'created', 'creates', 'creating' },
{ 'creation' },
{ 'creatives', 'creativity' },
{ 'creators' },
{ 'creatures' },
{ 'credentials' },
{ 'credibility' },
{ 'credit', 'credited', 'credits' },
{ 'creed' },
{ 'creek' },
{ 'cried' },
{ 'crimes' },
{ 'criminal', 'criminals' },
{ 'criminalisation' },
{ 'crippling' },
{ 'crises' },
{ 'crisis' },
{ 'crisp', 'crisps' },
{ 'criteria' },
{ 'critic', 'critical', 'criticism', 'criticized', 'critics' },
{ 'criticising' },
{ 'critique' },
{ 'crops' },
{ 'crossings' },
{ 'crossroads' },
{ 'crowd' },
{ 'crucial' },
{ 'crunched' },
{ 'crusade' },
{ 'crushed' },
{ 'crystalized' },
{ 'cudgel' },
{ 'cue' },
{ 'culmination' },
{ 'cult' },
{ 'cultivated', 'cultivates' },
{ 'cultural', 'culturally', 'culture', 'cultured', 'cultures' },
{ 'cup' },
{ 'curative' },
{ 'curate' },
{ 'cure', 'cured', 'cures' },
{ 'curia' },
{ 'curiosities' },
{ 'curiously' },
{ 'current', 'currently' },
{ 'custody' },
{ 'customer', 'customers', 'customs' },
{ 'customising' },
{ 'cut', 'cuts', 'cutting' },
{ 'cutesy' },
{ 'cyber' },
{ 'cyberbullying' },
{ 'czar' },
{ 'czechoslovakia' },
{ 'czerny' },
{ 'd' },
{ 'dad' },
{ 'daily' },
{ 'dairy' },
{ 'damage' },
{ 'damning' },
{ 'damnation' },
{ 'dampening' },
{ 'dan', 'dans' },
{ 'dana' },
{ 'dane', 'danes' },
{ 'danger', 'dangerous', 'dangers' },
{ 'daniel' },
{ 'daniela' },
{ 'danish' },
{ 'dares' },
{ 'dark' },
{ 'darker' },
{ 'dartmouth' },
{ 'data' },
{ 'database' },
{ 'date', 'dated' },
{ 'daughter' },
{ 'david' },
{ 'davila' },
{ 'day', 'days' },
{ 'dead' },
{ 'deal', 'dealing', 'deals' },
{ 'deane' },
{ 'dear' },
{ 'death', 'deaths' },
{ 'debate', 'debates' },
{ 'decade', 'decades' },
{ 'decay' },
{ 'december' },
{ 'decide', 'decided', 'decider' },
{ 'decision' },
{ 'declaration', 'declared' },
{ 'decline', 'declined', 'declines', 'declining' },
{ 'decreased', 'decreasing' },
{ 'dedicated', 'dedicating', 'dedication' },
{ 'deemed' },
{ 'deep' },
{ 'deepen' },
{ 'deeper' },
{ 'deeply' },
{ 'defeat', 'defeatism', 'defeats' },
{ 'defection' },
{ 'defend', 'defended', 'defenders', 'defending', 'defends' },
{ 'defenestration' },
{ 'defense', 'defensive' },
{ 'defied', 'defies', 'defying' },
{ 'defiance' },
{ 'deficiencies', 'deficiency', 'deficient' },
{ 'deficit' },
{ 'define', 'defines', 'defining' },
{ 'definition', 'definitive' },
{ 'deftly' },
{ 'defunding' },
{ 'degree' },
{ 'delayed', 'delaying' },
{ 'delegates' },
{ 'deliver', 'delivered' },
{ 'deluge' },
{ 'demagogues' },
{ 'demand', 'demanded', 'demanding', 'demands' },
{ 'demise' },
{ 'demo' },
{ 'democracies', 'democracy' },
{ 'democrat', 'democratic', 'democrats' },
{ 'democratised' },
{ 'demographic' },
{ 'demonstrably', 'demonstrate', 'demonstrations', 'demonstrators' },
{ 'demoralised' },
{ 'denied', 'deny', 'denying' },
{ 'denial' },
{ 'denmark' },
{ 'denote', 'denotes' },
{ 'denounce' },
{ 'depart', 'department', 'departments' },
{ 'depend', 'dependence', 'depends' },
{ 'depiction' },
{ 'deport', 'deportation', 'deportations', 'deported', 'deporting' },
{ 'deportees' },
{ 'depression' },
{ 'depth' },
{ 'deputy' },
{ 'descending' },
{ 'described' },
{ 'desensitisation' },
{ 'deserve', 'deserved', 'deserves' },
{ 'designated', 'designed', 'designer' },
{ 'desirable', 'desire', 'desires' },
{ 'desperately' },
{ 'despised' },
{ 'despite' },
{ 'desserts' },
{ 'destined' },
{ 'destroy', 'destroyed', 'destroys' },
{ 'destruction' },
{ 'detail', 'detailed', 'details' },
{ 'detain', 'detained' },
{ 'detainees' },
{ 'detected' },
{ 'detention', 'detentions' },
{ 'deterioration' },
{ 'determined', 'determining' },
{ 'detractors' },
{ 'detriment' },
{ 'deutschland' },
{ 'devastated', 'devastating' },
{ 'develop', 'developed', 'developing', 'development' },
{ 'device', 'devices' },
{ 'di' },
{ 'diabetes' },
{ 'diagnoses' },
{ 'diagnosis' },
{ 'dicastery' },
{ 'dictate', 'dictates', 'dictators' },
{ 'didn' },
{ 'die', 'died', 'dying' },
{ 'diet', 'diets' },
{ 'dietary' },
{ 'difference', 'different', 'differently', 'differing' },
{ 'difficult' },
{ 'difficulties' },
{ 'dig', 'digging' },
{ 'digested', 'digestion' },
{ 'digital', 'digits' },
{ 'dignity' },
{ 'dilemma' },
{ 'diluted', 'dilutions' },
{ 'diminish', 'diminishing' },
{ 'dinner' },
{ 'diocese' },
{ 'dip', 'dips' },
{ 'diplomacy' },
{ 'diplomat', 'diplomatic', 'diplomatically' },
{ 'dire' },
{ 'direct', 'directing', 'direction' },
{ 'directly' },
{ 'director' },
{ 'disabilities', 'disable', 'disables' },
{ 'disagree', 'disagreed' },
{ 'disappeared' },
{ 'disappointing', 'disappointments' },
{ 'disarray' },
{ 'disaster', 'disasters' },
{ 'disastrous' },
{ 'disavowed' },
{ 'discerning' },
{ 'disciplined', 'disciplines' },
{ 'disclaim' },
{ 'discontinuation' },
{ 'discouraging' },
{ 'discovered' },
{ 'discovery' },
{ 'discredited' },
{ 'discretionary' },
{ 'discriminate', 'discrimination' },
{ 'discussed', 'discussing', 'discussion', 'discussions' },
{ 'disease', 'diseases' },
{ 'disgraced' },
{ 'disguise', 'disguised' },
{ 'disgust' },
{ 'dish' },
{ 'disinformation' },
{ 'disintegrate' },
{ 'disjuncture' },
{ 'dislodge' },
{ 'dismantle', 'dismantling' },
{ 'dismissed' },
{ 'disney' },
{ 'disorientation' },
{ 'dispensed' },
{ 'display', 'displays' },
{ 'disposition' },
{ 'disproportionately' },
{ 'dispute', 'disputes' },
{ 'disregard' },
{ 'disrupted' },
{ 'dissent', 'dissented' },
{ 'dissidents' },
{ 'distance' },
{ 'distaste' },
{ 'distiller' },
{ 'distinction' },
{ 'distorting', 'distortion' },
{ 'distract' },
{ 'distressed' },
{ 'district' },
{ 'distrustful' },
{ 'dive' },
{ 'diverse', 'diversion', 'diversity' },
{ 'diversified', 'diversify' },
{ 'divest' },
{ 'divided' },
{ 'divisions', 'divisive' },
{ 'divorcees' },
{ 'divulging' },
{ 'doing' },
{ 'doctor', 'doctors' },
{ 'doctrine' },
{ 'dodo' },
{ 'doesn' },
{ 'dog', 'dogs' },
{ 'dogma' },
{ 'dogmatic' },
{ 'dollar', 'dollars' },
{ 'domestic', 'domestically' },
{ 'dominance', 'dominant', 'dominate', 'dominated', 'dominates' },
{ 'dominican' },
{ 'don' },
{ 'donald' },
{ 'done' },
{ 'door', 'doors' },
{ 'dots' },
{ 'double', 'doubled' },
{ 'doubt' },
{ 'doug' },
{ 'douglas' },
{ 'dow' },
{ 'down', 'downing' },
{ 'downgrade', 'downgraded', 'downgrades' },
{ 'downloads' },
{ 'downward' },
{ 'dozens' },
{ 'drafting' },
{ 'dragging' },
{ 'drained' },
{ 'drama' },
{ 'dramatic', 'dramatically' },
{ 'draws' },
{ 'drawn' },
{ 'drc' },
{ 'dream', 'dreams' },
{ 'drenon' },
{ 'dress', 'dresses' },
{ 'dried', 'dry' },
{ 'drink', 'drinking', 'drinks' },
{ 'drive', 'drives', 'driving' },
{ 'driver', 'drivers' },
{ 'drop', 'dropped', 'dropping' },
{ 'drug', 'drugs' },
{ 'drummed' },
{ 'dual' },
{ 'dubbed' },
{ 'duck' },
{ 'due' },
{ 'duly' },
{ 'dumbledore' },
{ 'dump' },
{ 'dunk' },
{ 'durable' },
{ 'during' },
{ 'dvd' },
{ 'dyer' },
{ 'dynamics' },
{ 'dysfunction' },
{ 'e' },
{ 'each' },
{ 'eadicicco' },
{ 'eagerly' },
{ 'earbuds' },
{ 'early' },
{ 'earlier' },
{ 'earliest' },
{ 'earnest' },
{ 'earth' },
{ 'ease' },
{ 'easy' },
{ 'easier' },
{ 'easily' },
{ 'east' },
{ 'eastern' },
{ 'eat', 'eating' },
{ 'eaters' },
{ 'echelons' },
{ 'echo' },
{ 'economic', 'economically', 'economics' },
{ 'economies', 'economy' },
{ 'economist' },
{ 'ecosystem', 'ecosystems' },
{ 'ecowarriors' },
{ 'ed' },
{ 'edge' },
{ 'edible' },
{ 'edits' },
{ 'edser' },
{ 'edt' },
{ 'education', 'educational', 'educators' },
{ 'effect', 'effective', 'effectively', 'effectiveness', 'effects' },
{ 'efficiency', 'efficient', 'efficiently' },
{ 'effort', 'efforts' },
{ 'egan' },
{ 'egregious' },
{ 'ehrlich' },
{ 'eichengrün' },
{ 'eight' },
{ 'either' },
{ 'el' },
{ 'elaborate' },
{ 'elderly' },
{ 'eldest' },
{ 'elect', 'elected', 'electing', 'election', 'elections' },
{ 'electoral', 'electorate' },
{ 'electronics' },
{ 'elegant' },
{ 'elements' },
{ 'elevator' },
{ 'eliminate' },
{ 'elite', 'elites', 'elitism' },
{ 'elixir', 'elixirs' },
{ 'elon' },
{ 'else' },
{ 'elsewhere' },
{ 'email', 'emailed', 'emails' },
{ 'embarrass', 'embarrassing' },
{ 'embedded' },
{ 'emblem' },
{ 'emboldened' },
{ 'embraces' },
{ 'embroiled' },
{ 'embryo', 'embryos' },
{ 'emerged', 'emergency', 'emerges', 'emerging' },
{ 'eminently' },
{ 'emissions' },
{ 'emotional', 'emotionally' },
{ 'emphasis' },
{ 'emphasised' },
{ 'employ', 'employed', 'employers', 'employing', 'employment' },
{ 'employee', 'employees' },
{ 'empowers' },
{ 'enable' },
{ 'enact' },
{ 'encapsulated' },
{ 'encounter' },
{ 'encourage', 'encouraged', 'encourages', 'encouraging' },
{ 'end', 'ended', 'ending', 'ends' },
{ 'endangered' },
{ 'endless' },
{ 'endlessly' },
{ 'endorsement', 'endorses', 'endorsing' },
{ 'endosperm' },
{ 'endowment', 'endowments' },
{ 'endure', 'endures' },
{ 'enemies', 'enemy' },
{ 'energetic' },
{ 'energy' },
{ 'energised' },
{ 'enforce', 'enforcement' },
{ 'engage', 'engaged', 'engagement', 'engaging' },
{ 'engineering', 'engines' },
{ 'england' },
{ 'enigma' },
{ 'enjoy', 'enjoys' },
{ 'enormous' },
{ 'enough' },
{ 'enraged' },
{ 'enrich', 'enriches' },
{ 'ensconced' },
{ 'ensure', 'ensuring' },
{ 'enter', 'entered', 'entering', 'enters' },
{ 'entertainment' },
{ 'enthusiasm' },
{ 'entire', 'entirely' },
{ 'entitled' },
{ 'entrenched' },
{ 'environment', 'environments' },
{ 'environmental' },
{ 'envision' },
{ 'enzyme' },
{ 'epidemic' },
{ 'episcopate' },
{ 'episode', 'episodes' },
{ 'equal', 'equalities', 'equality' },
{ 'equipment', 'equipped' },
{ 'equitably' },
{ 'equity' },
{ 'era' },
{ 'eradicate' },
{ 'erase' },
{ 'erasure' },
{ 'erdo' },
{ 'ernst' },
{ 'eroded' },
{ 'error', 'errors' },
{ 'escalate', 'escalated' },
{ 'especially' },
{ 'essence' },
{ 'essential', 'essentials' },
{ 'essex' },
{ 'essiedu' },
{ 'establish', 'established', 'establishment' },
{ 'estate' },
{ 'estimate', 'estimated', 'estimates', 'estimating' },
{ 'eternal' },
{ 'ethan' },
{ 'ethical' },
{ 'ethnic' },
{ 'eu' },
{ 'euphoria' },
{ 'europe' },
{ 'european' },
{ 'eurozone' },
{ 'euthanasia' },
{ 'evangelism' },
{ 'even', 'evening' },
{ 'event', 'events' },
{ 'eventually' },
{ 'ever' },
{ 'every' },
{ 'everybody' },
{ 'everyday' },
{ 'everyone' },
{ 'everything' },
{ 'everywhere' },
{ 'evicted' },
{ 'evidence', 'evident' },
{ 'evidenced' },
{ 'evil' },
{ 'evisceration' },
{ 'exact' },
{ 'exactitude' },
{ 'exactly' },
{ 'exaggerated', 'exaggeration' },
{ 'examined', 'examining' },
{ 'example', 'examples' },
{ 'exceeds' },
{ 'exceeding' },
{ 'excels' },
{ 'except', 'exception', 'exceptions' },
{ 'excess' },
{ 'excise' },
{ 'excited', 'excitement' },
{ 'exclusively' },
{ 'excusing' },
{ 'executed', 'executive' },
{ 'exempt', 'exemption' },
{ 'exhausting' },
{ 'exile' },
{ 'exist', 'existed', 'existence', 'existing', 'exists' },
{ 'existentialism' },
{ 'existentialist' },
{ 'exotic' },
{ 'expand', 'expanded', 'expanding' },
{ 'expect', 'expectation', 'expectations', 'expected', 'expects' },
{ 'expensive' },
{ 'experience', 'experiences', 'experiments' },
{ 'experienced', 'experiencing' },
{ 'experimental' },
{ 'expert', 'experts' },
{ 'expertly' },
{ 'explain', 'explains' },
{ 'explanation' },
{ 'exploit', 'exploiting' },
{ 'exponential' },
{ 'exporter', 'exports' },
{ 'exposed', 'exposing' },
{ 'exposure' },
{ 'express', 'expressed', 'expressing', 'expression', 'expressions' },
{ 'expulsion' },
{ 'extend', 'extended' },
{ 'extension' },
{ 'extent' },
{ 'external' },
{ 'extinct', 'extinction' },
{ 'extra' },
{ 'extracting' },
{ 'extreme', 'extremism' },
{ 'extremist' },
{ 'exude' },
{ 'eye', 'eyes' },
{ 'f' },
{ 'fabric', 'fabricating' },
{ 'face', 'faced', 'faces', 'facing' },
{ 'facebook' },
{ 'facilities', 'facility' },
{ 'facilitate' },
{ 'fact', 'facts' },
{ 'faction', 'factionalism' },
{ 'factor', 'factored', 'factors' },
{ 'factories', 'factory' },
{ 'faculty' },
{ 'fade' },
{ 'fail', 'failed', 'failing' },
{ 'failure', 'failures' },
{ 'fair' },
{ 'faith' },
{ 'fake' },
{ 'fall', 'falling', 'falls' },
{ 'fallen' },
{ 'families', 'family' },
{ 'familiar' },
{ 'famous' },
{ 'fans' },
{ 'fanatical' },
{ 'fandom' },
{ 'fantasy' },
{ 'fantastically' },
{ 'far' },
{ 'farage', 'faragism' },
{ 'farbenfabriken' },
{ 'farm' },
{ 'fascism' },
{ 'fashion', 'fashionable' },
{ 'fast' },
{ 'fastest' },
{ 'fat', 'fats' },
{ 'fate' },
{ 'father' },
{ 'fauna' },
{ 'favors' },
{ 'favour' },
{ 'favourite' },
{ 'fe' },
{ 'fear', 'feared', 'fearful', 'fearing', 'fears' },
{ 'feature', 'features' },
{ 'february' },
{ 'federal' },
{ 'feeding', 'feeds' },
{ 'feel', 'feeling', 'feelings', 'feels' },
{ 'felix' },
{ 'fell' },
{ 'fellow' },
{ 'felt' },
{ 'female' },
{ 'feminine' },
{ 'feminists' },
{ 'fend' },
{ 'fertile' },
{ 'fetishisation' },
{ 'feud' },
{ 'fever' },
{ 'few' },
{ 'fewer' },
{ 'fibre' },
{ 'fiction', 'fictional' },
{ 'fide' },
{ 'field', 'fields' },
{ 'fierce', 'fiercely' },
{ 'fight', 'fighting', 'fights' },
{ 'figure', 'figured', 'figures' },
{ 'filed' },
{ 'filipino' },
{ 'fill', 'filled' },
{ 'films' },
{ 'filtered' },
{ 'final', 'finally' },
{ 'finance', 'finances' },
{ 'financial' },
{ 'find', 'finding', 'findings' },
{ 'fine', 'finely' },
{ 'finest' },
{ 'finger' },
{ 'finished' },
{ 'finland' },
{ 'fire', 'firing' },
{ 'firm', 'firms' },
{ 'first' },
{ 'fitness' },
{ 'five' },
{ 'fix' },
{ 'flag', 'flagged' },
{ 'flakes' },
{ 'flared' },
{ 'flattering' },
{ 'flavourings' },
{ 'flaw' },
{ 'fleming' },
{ 'fly' },
{ 'flight', 'flights' },
{ 'flinch' },
{ 'flipped' },
{ 'floating' },
{ 'floods' },
{ 'floor' },
{ 'florey' },
{ 'florid' },
{ 'florida' },
{ 'flour', 'flours' },
{ 'flourishing' },
{ 'flsa' },
{ 'fluid', 'fluids' },
{ 'flurry' },
{ 'focus' },
{ 'focused' },
{ 'folk' },
{ 'follow', 'followed', 'followers', 'following' },
{ 'food', 'foods' },
{ 'fool', 'fooling' },
{ 'foolish' },
{ 'foot' },
{ 'footage' },
{ 'football' },
{ 'force', 'forced', 'forces', 'forcing' },
{ 'forecast', 'forecasts' },
{ 'forefront' },
{ 'foreign', 'foreigners' },
{ 'forest' },
{ 'forever' },
{ 'forge' },
{ 'forget' },
{ 'forgot' },
{ 'forgotten' },
{ 'form', 'formative', 'formed', 'forms' },
{ 'formal' },
{ 'former' },
{ 'formula', 'formulas' },
{ 'fortification' },
{ 'fortified' },
{ 'forum' },
{ 'forward' },
{ 'foster', 'fostering' },
{ 'foul' },
{ 'found', 'founded', 'founding' },
{ 'foundation' },
{ 'founder' },
{ 'four' },
{ 'fourth' },
{ 'fox' },
{ 'fragile' },
{ 'fragmented' },
{ 'frame' },
{ 'france' },
{ 'franchise' },
{ 'franchisee' },
{ 'francis' },
{ 'frankly' },
{ 'fraud' },
{ 'fraudsters' },
{ 'fraught' },
{ 'frayed' },
{ 'frederick' },
{ 'free' },
{ 'freedom' },
{ 'freely' },
{ 'freising' },
{ 'frequency' },
{ 'frequently' },
{ 'fridolin' },
{ 'friedrich' },
{ 'friend', 'friends' },
{ 'friendly' },
{ 'friendship' },
{ 'fright' },
{ 'frightened' },
{ 'frisch' },
{ 'front', 'fronts' },
{ 'frontier' },
{ 'frontrunner' },
{ 'frost' },
{ 'froze' },
{ 'fruit', 'fruitful', 'fruits' },
{ 'fruition' },
{ 'frustrated', 'frustrating', 'frustration' },
{ 'fuels' },
{ 'full' },
{ 'fuller' },
{ 'fully' },
{ 'fullscreen' },
{ 'fun' },
{ 'function' },
{ 'fund', 'funding', 'funds' },
{ 'fundamental', 'fundamentally' },
{ 'fundamentalist' },
{ 'funk' },
{ 'funky' },
{ 'funny' },
{ 'furious' },
{ 'furnaces' },
{ 'furniture' },
{ 'furore' },
{ 'further' },
{ 'furthermore' },
{ 'fuss' },
{ 'futile' },
{ 'future' },
{ 'für' },
{ 'gas' },
{ 'gadfly' },
{ 'gadgets' },
{ 'gain', 'gained' },
{ 'galaxy' },
{ 'game' },
{ 'gang' },
{ 'gap' },
{ 'garcia' },
{ 'gateway' },
{ 'gather' },
{ 'gave' },
{ 'gavin' },
{ 'gay' },
{ 'gaza' },
{ 'geared' },
{ 'gender' },
{ 'gene' },
{ 'general', 'generally', 'generated', 'generation', 'generations', 'generative', 'generic' },
{ 'genetic' },
{ 'genius' },
{ 'genocide' },
{ 'genome' },
{ 'genre' },
{ 'genuflection' },
{ 'genuine', 'genuinely' },
{ 'geopolitical' },
{ 'georg', 'george' },
{ 'georgetown' },
{ 'germ', 'germs' },
{ 'german' },
{ 'germany' },
{ 'gerrit' },
{ 'get', 'gets', 'getting' },
{ 'ghana' },
{ 'ghanaian' },
{ 'ghibli' },
{ 'giant', 'giants' },
{ 'gift' },
{ 'gill' },
{ 'girl', 'girls' },
{ 'girlfriend' },
{ 'give', 'gives', 'giving' },
{ 'given' },
{ 'glance' },
{ 'glaring' },
{ 'glimmer' },
{ 'global', 'globalization', 'globally' },
{ 'globalisation' },
{ 'globe' },
{ 'gloom' },
{ 'gloss' },
{ 'glucan' },
{ 'glucose' },
{ 'glycaemic' },
{ 'go', 'going' },
{ 'goal', 'goals' },
{ 'goblet' },
{ 'god' },
{ 'goes' },
{ 'gokim' },
{ 'gone' },
{ 'good', 'goods' },
{ 'goodman' },
{ 'google' },
{ 'gop' },
{ 'gorillas' },
{ 'gospel' },
{ 'got' },
{ 'gotten' },
{ 'gourinchas' },
{ 'gov' },
{ 'governance', 'governing', 'government', 'governments' },
{ 'grabbed' },
{ 'grace' },
{ 'gracious' },
{ 'grade' },
{ 'graders' },
{ 'graduate', 'graduates' },
{ 'grain', 'grains' },
{ 'grams' },
{ 'grand' },
{ 'grandchildren' },
{ 'granola', 'granolas' },
{ 'grant', 'granted', 'granting', 'grants' },
{ 'graphically' },
{ 'grasses' },
{ 'gratify' },
{ 'gravel' },
{ 'great', 'greatness' },
{ 'greater' },
{ 'greatest' },
{ 'greed' },
{ 'greeks' },
{ 'green', 'greens' },
{ 'greenland' },
{ 'greet', 'greeted' },
{ 'greg' },
{ 'grew' },
{ 'grey' },
{ 'grievance', 'grievances' },
{ 'griggs' },
{ 'grinding' },
{ 'grint' },
{ 'gripes' },
{ 'grocer' },
{ 'groceries', 'grocery' },
{ 'gross' },
{ 'ground', 'grounded', 'grounds' },
{ 'groundwork' },
{ 'group', 'groups' },
{ 'grow', 'growing', 'grows' },
{ 'grown' },
{ 'grownup' },
{ 'growth' },
{ 'guardians' },
{ 'guess' },
{ 'guidelines' },
{ 'guinea' },
{ 'guinean' },
{ 'guitarist' },
{ 'gun' },
{ 'guru' },
{ 'gushed' },
{ 'gut', 'guts' },
{ 'guterres' },
{ 'guys' },
{ 'h' },
{ 'haberlandt' },
{ 'habits' },
{ 'habitat' },
{ 'hacked' },
{ 'hackers' },
{ 'hagrid' },
{ 'haidt' },
{ 'hailed', 'hailing' },
{ 'half' },
{ 'halls' },
{ 'halting' },
{ 'hamas' },
{ 'hammering' },
{ 'hampering' },
{ 'hand', 'handful', 'handing', 'hands' },
{ 'handle' },
{ 'handsome' },
{ 'hanging' },
{ 'haniyeh' },
{ 'happen', 'happened', 'happening', 'happens' },
{ 'happy' },
{ 'happier' },
{ 'harness' },
{ 'harassment' },
{ 'hard' },
{ 'harder' },
{ 'hardline' },
{ 'harm', 'harmed', 'harmful' },
{ 'harman' },
{ 'harmless' },
{ 'harmony' },
{ 'harris', 'harry' },
{ 'harriet' },
{ 'harsh', 'harshness' },
{ 'harshly' },
{ 'haruhi' },
{ 'harvard' },
{ 'harvested', 'harvesting' },
{ 'harvey' },
{ 'harvie' },
{ 'hashemi' },
{ 'hasn' },
{ 'hasty' },
{ 'hate', 'hated', 'hates' },
{ 'hatred' },
{ 'hauling' },
{ 'haunted' },
{ 'having' },
{ 'haven' },
{ 'hawkeye' },
{ 'hazardous', 'hazards' },
{ 'hbo' },
{ 'head', 'headed', 'heading', 'heads' },
{ 'headline', 'headlines' },
{ 'headwinds' },
{ 'heal', 'healing' },
{ 'health' },
{ 'healthy' },
{ 'healthier' },
{ 'hear' },
{ 'heard' },
{ 'heart', 'hearts' },
{ 'heartbreaking' },
{ 'heat', 'heating' },
{ 'heatedly' },
{ 'heavy' },
{ 'heavily' },
{ 'hebron' },
{ 'heels' },
{ 'heerulff' },
{ 'hegel' },
{ 'hegelians' },
{ 'hegseth' },
{ 'heidegger' },
{ 'height', 'heights' },
{ 'held' },
{ 'hell' },
{ 'hellish' },
{ 'helm' },
{ 'help', 'helped', 'helping', 'helps' },
{ 'helplessness' },
{ 'helpline' },
{ 'hence' },
{ 'heraclitus' },
{ 'herald' },
{ 'herbs' },
{ 'here' },
{ 'heritable' },
{ 'heritage' },
{ 'hero', 'heroes' },
{ 'heroism' },
{ 'herself' },
{ 'hershey' },
{ 'hesitancy' },
{ 'heterodox' },
{ 'hewed' },
{ 'hides' },
{ 'hierarchies', 'hierarchy' },
{ 'high', 'highs' },
{ 'higher' },
{ 'highest' },
{ 'highly' },
{ 'highlighted', 'highlighting' },
{ 'hike', 'hikes' },
{ 'him' },
{ 'himself' },
{ 'hinder' },
{ 'hinge' },
{ 'hinted' },
{ 'hire', 'hires', 'hiring' },
{ 'historic', 'historical', 'historically' },
{ 'history' },
{ 'hit', 'hits', 'hitting' },
{ 'hodge' },
{ 'hoffmann' },
{ 'hold', 'holding', 'holds' },
{ 'holder' },
{ 'hollen' },
{ 'homan' },
{ 'home', 'homes' },
{ 'homeland' },
{ 'homemakers' },
{ 'homicidal' },
{ 'homophobia' },
{ 'homosexuality', 'homosexuals' },
{ 'honestly' },
{ 'honor' },
{ 'hope', 'hoped', 'hopeful', 'hopes' },
{ 'hopelessly' },
{ 'hormonal', 'hormone', 'hormones' },
{ 'horribly' },
{ 'horrific' },
{ 'horrified', 'horrifies' },
{ 'hospital', 'hospitality', 'hospitalization', 'hospitals' },
{ 'host' },
{ 'hostile', 'hostility' },
{ 'hotel' },
{ 'hounded', 'hounds' },
{ 'hour', 'hours' },
{ 'house', 'houses' },
{ 'household', 'households' },
{ 'houston' },
{ 'how' },
{ 'howard' },
{ 'however' },
{ 'https' },
{ 'hub' },
{ 'hubris' },
{ 'huge', 'hugely' },
{ 'human', 'humane', 'humanities', 'humanity', 'humans' },
{ 'humanoid' },
{ 'humour' },
{ 'hundreds' },
{ 'hungary' },
{ 'hungarian' },
{ 'hungry' },
{ 'hungrier' },
{ 'hurled' },
{ 'hurried' },
{ 'hurricane' },
{ 'hurt', 'hurtful' },
{ 'hybrid' },
{ 'hypothesis' },
{ 'ice' },
{ 'iconic' },
{ 'idea', 'ideas' },
{ 'ideal' },
{ 'idealise' },
{ 'identities', 'identity' },
{ 'identified', 'identify' },
{ 'ideological', 'ideologies', 'ideology' },
{ 'igniting' },
{ 'ignorance', 'ignore', 'ignoring' },
{ 'ii' },
{ 'ill', 'illness', 'illnesses' },
{ 'illegal', 'illegally' },
{ 'illiberal' },
{ 'illustrate' },
{ 'image', 'images' },
{ 'imagine', 'imagined' },
{ 'imbued' },
{ 'imf' },
{ 'imitation' },
{ 'immediate' },
{ 'immerse', 'immersed', 'immersion' },
{ 'immigrants', 'immigration' },
{ 'imminent' },
{ 'immobilised' },
{ 'immoral' },
{ 'immune' },
{ 'impact' },
{ 'impede' },
{ 'imperfections' },
{ 'implanted' },
{ 'implement', 'implementation', 'implemented' },
{ 'implications' },
{ 'import', 'importance', 'important', 'imports' },
{ 'importantly' },
{ 'impose', 'imposing' },
{ 'imposition' },
{ 'impossible', 'impossibly' },
{ 'impression', 'impressive' },
{ 'improbable' },
{ 'improve' },
{ 'impulse', 'impulses' },
{ 'impure' },
{ 'inadequate' },
{ 'inadvertently' },
{ 'inappropriate' },
{ 'inception' },
{ 'incessant' },
{ 'incident', 'incidents' },
{ 'incidentally' },
{ 'inclined' },
{ 'include', 'included', 'includes', 'including' },
{ 'inclusion' },
{ 'incognito' },
{ 'incoming' },
{ 'incorrectly' },
{ 'increase', 'increased', 'increases', 'increasing' },
{ 'increasingly' },
{ 'incredibly' },
{ 'incubator' },
{ 'indeed' },
{ 'independence' },
{ 'index' },
{ 'india' },
{ 'indicate', 'indicated', 'indication' },
{ 'indictment' },
{ 'indigenous' },
{ 'indirect' },
{ 'indirectly' },
{ 'individual', 'individualism', 'individuality', 'individuals' },
{ 'indulge' },
{ 'industrial', 'industries', 'industry' },
{ 'ineducable' },
{ 'inevitable', 'inevitably' },
{ 'infantilising' },
{ 'infections' },
{ 'infectious' },
{ 'infiltrates' },
{ 'infinite' },
{ 'inflation' },
{ 'inflict' },
{ 'influence', 'influencing' },
{ 'influential' },
{ 'inform', 'informal', 'information' },
{ 'infractions' },
{ 'infringed' },
{ 'ingredient', 'ingredients' },
{ 'inhaled' },
{ 'inherently' },
{ 'inhibition' },
{ 'inhibitors' },
{ 'inhumane' },
{ 'initial', 'initially', 'initiative', 'initiatives' },
{ 'inject', 'injecting' },
{ 'injured' },
{ 'injuries' },
{ 'inner' },
{ 'innocence', 'innocent' },
{ 'innovates', 'innovation', 'innovators' },
{ 'inoculation' },
{ 'input' },
{ 'insane' },
{ 'inside', 'insider' },
{ 'insidious', 'insidiously' },
{ 'insight' },
{ 'insistence', 'insistent', 'insists' },
{ 'inspire' },
{ 'instagram' },
{ 'instalment' },
{ 'instance', 'instances' },
{ 'instant' },
{ 'instead' },
{ 'instinctively', 'instincts' },
{ 'institute', 'institutes', 'institution', 'institutional', 'institutions' },
{ 'institutionalising' },
{ 'instructions', 'instructive', 'instructs' },
{ 'insulin' },
{ 'intake', 'intakes' },
{ 'integral', 'integrated' },
{ 'intellectual', 'intellectually' },
{ 'intelligence' },
{ 'intend', 'intended' },
{ 'intense', 'intensely', 'intensity' },
{ 'intent', 'intention' },
{ 'interact', 'interaction', 'interactions' },
{ 'intercepted' },
{ 'interest', 'interested', 'interesting', 'interests' },
{ 'interestingly' },
{ 'interior' },
{ 'interlinked' },
{ 'intermission' },
{ 'internal', 'international', 'internment' },
{ 'internet' },
{ 'interpret', 'interpretation' },
{ 'interracial' },
{ 'intersect', 'intersection' },
{ 'intertwined' },
{ 'intervention' },
{ 'interview' },
{ 'intifadas' },
{ 'intimate', 'intimately' },
{ 'intimidate', 'intimidating' },
{ 'into' },
{ 'intolerance' },
{ 'intricacies' },
{ 'intrigued' },
{ 'intrinsically' },
{ 'introduce', 'introduced', 'introducing' },
{ 'introduction' },
{ 'intubated' },
{ 'intuitive', 'intuitively' },
{ 'invaded' },
{ 'invalidate' },
{ 'invariably' },
{ 'invasion' },
{ 'invented' },
{ 'inventor' },
{ 'invest', 'invested', 'investing', 'investment', 'investments' },
{ 'investigate', 'investigated', 'investigating', 'investigation', 'investigations' },
{ 'investor', 'investors' },
{ 'invisible' },
{ 'invited', 'inviting' },
{ 'involve', 'involved', 'involvement', 'involves', 'involving' },
{ 'iowa' },
{ 'ip' },
{ 'iphone', 'iphones' },
{ 'irs' },
{ 'iran' },
{ 'iraq' },
{ 'ireland' },
{ 'iron', 'ironic' },
{ 'irrationalism' },
{ 'irredeemable' },
{ 'irrespective' },
{ 'irretrievably' },
{ 'irrevocably' },
{ 'irritating' },
{ 'irwin' },
{ 'isi' },
{ 'islam', 'islamic' },
{ 'ismail' },
{ 'isn' },
{ 'isolate', 'isolated', 'isolating', 'isolation' },
{ 'israelis' },
{ 'israel' },
{ 'issue', 'issued', 'issues' },
{ 'italy' },
{ 'italian' },
{ 'itself' },
{ 'ivanov' },
{ 'ives' },
{ 'ivy' },
{ 'jab' },
{ 'jack' },
{ 'jacket' },
{ 'jagged' },
{ 'jail' },
{ 'jair' },
{ 'james' },
{ 'jane' },
{ 'january' },
{ 'japanese' },
{ 'jasmin' },
{ 'jason' },
{ 'jay' },
{ 'jd' },
{ 'jerome' },
{ 'jersey' },
{ 'jerusalem' },
{ 'jesuit' },
{ 'jews' },
{ 'jewish' },
{ 'jihadist' },
{ 'jinping' },
{ 'job', 'jobs' },
{ 'joe' },
{ 'john' },
{ 'johnson' },
{ 'join', 'joined', 'joining', 'joins' },
{ 'jointly' },
{ 'joke' },
{ 'jolly' },
{ 'jonas' },
{ 'jonathan' },
{ 'jones' },
{ 'josh' },
{ 'journal' },
{ 'journalist' },
{ 'journey' },
{ 'jpost' },
{ 'jr' },
{ 'judge', 'judged', 'judges' },
{ 'judgment', 'judgments' },
{ 'judiciary' },
{ 'judul' },
{ 'juice' },
{ 'july' },
{ 'jump', 'jumped' },
{ 'june' },
{ 'junk' },
{ 'jurisdiction' },
{ 'just' },
{ 'justice' },
{ 'justification' },
{ 'justify' },
{ 'k' },
{ 'karoline' },
{ 'keen' },
{ 'keep', 'keeping' },
{ 'kefir' },
{ 'keir' },
{ 'kellogg' },
{ 'kemi' },
{ 'kenan' },
{ 'kennedy' },
{ 'kenya' },
{ 'kept' },
{ 'key' },
{ 'khalil' },
{ 'khan' },
{ 'kicking' },
{ 'kids' },
{ 'kidnapped' },
{ 'kierkegaard' },
{ 'kierkegaardians' },
{ 'kill', 'killed', 'killing' },
{ 'kilmar' },
{ 'kin' },
{ 'kind' },
{ 'kindergartners' },
{ 'king' },
{ 'kingdom' },
{ 'kinshasa' },
{ 'kirby' },
{ 'kits' },
{ 'knees' },
{ 'kneeling' },
{ 'knelt' },
{ 'knew' },
{ 'knocked' },
{ 'know', 'knows' },
{ 'knowledge' },
{ 'known' },
{ 'kodwo' },
{ 'korea' },
{ 'lab' },
{ 'labelling', 'labels' },
{ 'labor' },
{ 'laboratories', 'laboratory' },
{ 'labour' },
{ 'lack', 'lacking' },
{ 'lactose' },
{ 'laid' },
{ 'lamas' },
{ 'land', 'landed', 'lands' },
{ 'landfill' },
{ 'landmark' },
{ 'landscapes' },
{ 'landslide' },
{ 'langlitz' },
{ 'language' },
{ 'languished' },
{ 'laptops' },
{ 'lara' },
{ 'large', 'largely' },
{ 'larger' },
{ 'largest' },
{ 'larry' },
{ 'last', 'lasted', 'lasting' },
{ 'late' },
{ 'later' },
{ 'latest' },
{ 'latin' },
{ 'latinx' },
{ 'latter' },
{ 'launched', 'launching' },
{ 'law', 'lawful', 'laws' },
{ 'lawless' },
{ 'lawmakers', 'lawmaking' },
{ 'lawnmowers' },
{ 'lawsuits' },
{ 'lawyers' },
{ 'lay' },
{ 'layer', 'layers' },
{ 'layout' },
{ 'ldl' },
{ 'le' },
{ 'lead', 'leading', 'leads' },
{ 'leader', 'leaders' },
{ 'leadership' },
{ 'league' },
{ 'leaning', 'leanings', 'leans' },
{ 'learn', 'learned', 'learning' },
{ 'learnt' },
{ 'least' },
{ 'leave', 'leaves', 'leaving' },
{ 'leavitt' },
{ 'led' },
{ 'left' },
{ 'leftwing' },
{ 'legs' },
{ 'legal', 'legality', 'legally' },
{ 'legalisation' },
{ 'legendary' },
{ 'legislation', 'legislative', 'legislators' },
{ 'legislatures' },
{ 'legitimate' },
{ 'legitimacy' },
{ 'lens' },
{ 'lengths' },
{ 'lesbian', 'lesbians' },
{ 'less' },
{ 'lessen' },
{ 'lessons' },
{ 'let', 'letting' },
{ 'lethal' },
{ 'leukocytes' },
{ 'level', 'levels' },
{ 'levers' },
{ 'levied', 'levies' },
{ 'levitate' },
{ 'liability' },
{ 'liberal', 'liberation' },
{ 'liberties', 'liberty' },
{ 'lies' },
{ 'life' },
{ 'lifeguarding' },
{ 'lift' },
{ 'light' },
{ 'lightning' },
{ 'like', 'liked', 'likely' },
{ 'likelihood' },
{ 'likewise' },
{ 'limbs' },
{ 'limit', 'limited', 'limits' },
{ 'linda' },
{ 'line', 'lines' },
{ 'lingers' },
{ 'link', 'linked', 'links' },
{ 'linkedin' },
{ 'lipoprotein' },
{ 'liquor' },
{ 'lisa' },
{ 'list', 'listed', 'lists' },
{ 'literature' },
{ 'lithgow' },
{ 'lithuania' },
{ 'litmus' },
{ 'little' },
{ 'liturgical' },
{ 'liturgy' },
{ 'live', 'lived', 'lives', 'living' },
{ 'll' },
{ 'lloyds' },
{ 'loaded', 'loads' },
{ 'loathes', 'loathing' },
{ 'lobby', 'lobbying' },
{ 'loblaw' },
{ 'local' },
{ 'lochfield' },
{ 'lock', 'locked' },
{ 'logs' },
{ 'logic', 'logical' },
{ 'logo' },
{ 'london' },
{ 'long' },
{ 'longer' },
{ 'look', 'looked', 'looking', 'looks' },
{ 'loops' },
{ 'loosening' },
{ 'lord' },
{ 'lose', 'losing' },
{ 'losses' },
{ 'lost' },
{ 'lot', 'lots' },
{ 'loud' },
{ 'louder' },
{ 'loudly' },
{ 'louisiana' },
{ 'love', 'loved', 'loves' },
{ 'low' },
{ 'lower', 'lowered' },
{ 'lowest' },
{ 'loyal' },
{ 'luckett' },
{ 'lucrative' },
{ 'ludwig' },
{ 'luis' },
{ 'lumping' },
{ 'lunacy' },
{ 'lunatics' },
{ 'lunged', 'lungs' },
{ 'lymphomas' },
{ 'lysis' },
{ 'lysozyme' },
{ 'm' },
{ 'machine' },
{ 'machinery' },
{ 'mad' },
{ 'made' },
{ 'madman' },
{ 'maga' },
{ 'magic', 'magical' },
{ 'mahdawi' },
{ 'mahmoud' },
{ 'mail' },
{ 'main' },
{ 'mainstream' },
{ 'maintained', 'maintaining' },
{ 'major', 'majority' },
{ 'make', 'makes', 'making' },
{ 'maker', 'makers' },
{ 'male', 'males' },
{ 'maligning' },
{ 'malik' },
{ 'malnourishment' },
{ 'malware' },
{ 'mammoth' },
{ 'man' },
{ 'manage', 'managed', 'management', 'manages', 'managing' },
{ 'mandate', 'mandates' },
{ 'many' },
{ 'maniacal' },
{ 'manifest', 'manifestation', 'manifesting' },
{ 'manifestos' },
{ 'manila' },
{ 'manufacturer', 'manufacturers', 'manufacturing' },
{ 'mao' },
{ 'map' },
{ 'maple' },
{ 'maqbool' },
{ 'mars' },
{ 'marathon' },
{ 'marc' },
{ 'march' },
{ 'marco' },
{ 'margaret' },
{ 'marginal', 'margins' },
{ 'mary' },
{ 'marine' },
{ 'mark', 'marked' },
{ 'marker' },
{ 'market', 'marketer', 'marketing', 'markets' },
{ 'marquette' },
{ 'marriage' },
{ 'martha' },
{ 'martin' },
{ 'marx' },
{ 'marxist', 'marxists' },
{ 'maryland' },
{ 'mask' },
{ 'masquerade' },
{ 'mass' },
{ 'massachusetts' },
{ 'massive', 'massively' },
{ 'master', 'masterfully' },
{ 'material', 'materializing', 'materially' },
{ 'maternal' },
{ 'math' },
{ 'mathematical', 'mathematically', 'mathematics' },
{ 'mathematician', 'mathematicians' },
{ 'matter', 'matters' },
{ 'mature', 'maturity' },
{ 'max' },
{ 'maximalist' },
{ 'maximum' },
{ 'maybe' },
{ 'mayhem' },
{ 'mayor' },
{ 'mazur' },
{ 'mcgonagall' },
{ 'meal' },
{ 'mean', 'meaning', 'meanness', 'means' },
{ 'meant' },
{ 'meanwhile' },
{ 'measles' },
{ 'measure', 'measures' },
{ 'meats' },
{ 'meatpacking' },
{ 'mechlorethamine' },
{ 'media' },
{ 'medical', 'medications' },
{ 'medicine' },
{ 'meet', 'meeting', 'meetings' },
{ 'mejr' },
{ 'mel' },
{ 'melancholy' },
{ 'melanie' },
{ 'member', 'members' },
{ 'memefare' },
{ 'memorable' },
{ 'memorialized', 'memory' },
{ 'men' },
{ 'menacing' },
{ 'mental', 'mentally' },
{ 'mentioned', 'mentioning' },
{ 'merely' },
{ 'message', 'messages', 'messaging' },
{ 'messy' },
{ 'met' },
{ 'meta' },
{ 'metal' },
{ 'methods' },
{ 'metropolitan' },
{ 'mette' },
{ 'mexican' },
{ 'mexico' },
{ 'meyer' },
{ 'michael' },
{ 'michaela' },
{ 'microbes' },
{ 'microbiome' },
{ 'micronutrients' },
{ 'middle' },
{ 'mighty' },
{ 'migrant', 'migrants' },
{ 'milan' },
{ 'mildly' },
{ 'miliband' },
{ 'military' },
{ 'milk' },
{ 'mill', 'milled' },
{ 'millennia' },
{ 'million', 'millions' },
{ 'mind', 'minded' },
{ 'mindlessly' },
{ 'mined', 'mines' },
{ 'minerals' },
{ 'minimal' },
{ 'minimum' },
{ 'minister' },
{ 'minor', 'minority', 'minors' },
{ 'minutes' },
{ 'mirror' },
{ 'misinterpreted' },
{ 'misleading' },
{ 'misogyny' },
{ 'misread' },
{ 'misrepresented' },
{ 'miss', 'missed', 'missing' },
{ 'mission' },
{ 'missionary' },
{ 'mistake', 'mistakes' },
{ 'mistaken' },
{ 'mistakenly' },
{ 'misunderstanding' },
{ 'mix', 'mixed' },
{ 'mixture' },
{ 'mmr' },
{ 'mo' },
{ 'mobile' },
{ 'mocking' },
{ 'mode' },
{ 'model', 'models' },
{ 'moderate' },
{ 'modern', 'modernity', 'modernize' },
{ 'mohsen' },
{ 'mold', 'molds' },
{ 'moment' },
{ 'momentum' },
{ 'monday' },
{ 'monetary' },
{ 'money' },
{ 'monitors' },
{ 'monstrousness' },
{ 'month', 'months' },
{ 'monthly' },
{ 'monumental' },
{ 'moral', 'morale', 'morality' },
{ 'morass' },
{ 'more' },
{ 'moreover' },
{ 'morning' },
{ 'mortality' },
{ 'most' },
{ 'mostly' },
{ 'mother', 'mothers' },
{ 'motion' },
{ 'motivation', 'motivations' },
{ 'mountain' },
{ 'mouse' },
{ 'move', 'moved', 'moves' },
{ 'movement' },
{ 'movie', 'movies' },
{ 'mps' },
{ 'mr' },
{ 'ms' },
{ 'much' },
{ 'mucus' },
{ 'muddy' },
{ 'muesli' },
{ 'muggles' },
{ 'multiple' },
{ 'multitudes' },
{ 'mum' },
{ 'mumps' },
{ 'munich' },
{ 'murder', 'murders' },
{ 'muscly' },
{ 'music' },
{ 'musk' },
{ 'muslims' },
{ 'mustards' },
{ 'mutation' },
{ 'myriad' },
{ 'myself' },
{ 'mystery' },
{ 'mytu' },
{ 'nader' },
{ 'naive', 'naively' },
{ 'nama' },
{ 'name', 'named', 'namely', 'names' },
{ 'narrative', 'narratives' },
{ 'narrow' },
{ 'nasal' },
{ 'nation', 'national', 'nationality', 'nations' },
{ 'nationalist' },
{ 'native', 'natives' },
{ 'nato' },
{ 'natural', 'nature' },
{ 'navigate', 'navigated', 'navigating' },
{ 'naïve' },
{ 'near', 'nearing' },
{ 'nearly' },
{ 'neatly' },
{ 'necessities' },
{ 'necessary' },
{ 'necessarily' },
{ 'need', 'needed', 'needs' },
{ 'negative', 'negatively' },
{ 'neglected' },
{ 'negotiating', 'negotiations' },
{ 'neighbors' },
{ 'neither' },
{ 'nelson' },
{ 'neofascist' },
{ 'nesrine' },
{ 'net' },
{ 'netflix' },
{ 'network', 'networking' },
{ 'neurodiversity' },
{ 'neuron' },
{ 'neurotransmitters' },
{ 'neutral' },
{ 'never' },
{ 'nevertheless' },
{ 'new' },
{ 'news' },
{ 'newsom' },
{ 'newspaper' },
{ 'newsworthy' },
{ 'next' },
{ 'ngos' },
{ 'nhs' },
{ 'nicaragua' },
{ 'nick' },
{ 'nicolas' },
{ 'nigel' },
{ 'night', 'nights' },
{ 'nihilistic' },
{ 'nine' },
{ 'nitrogen' },
{ 'nkan' },
{ 'no' },
{ 'nobel' },
{ 'nobelists' },
{ 'nobody' },
{ 'nomination' },
{ 'none' },
{ 'nonetheless' },
{ 'nonlinear' },
{ 'nonprofit' },
{ 'nonsense', 'nonsensical' },
{ 'nonsexual' },
{ 'nor' },
{ 'norms' },
{ 'normalization', 'normally' },
{ 'north' },
{ 'nostalgic' },
{ 'nostalgia' },
{ 'not' },
{ 'notable' },
{ 'notatum' },
{ 'note', 'notes' },
{ 'notebooks' },
{ 'nothing' },
{ 'notice', 'noticed' },
{ 'notification' },
{ 'notion' },
{ 'notorious', 'notoriously' },
{ 'nova' },
{ 'novel', 'novels' },
{ 'now' },
{ 'nowhere' },
{ 'nuclear' },
{ 'nucleoside' },
{ 'number', 'numbers' },
{ 'numerous' },
{ 'nurse', 'nurses' },
{ 'nurture', 'nurturing' },
{ 'nuts' },
{ 'nutrient', 'nutrients' },
{ 'nutrition' },
{ 'nutritious' },
{ 'nutritionist' },
{ 'oat', 'oats' },
{ 'oatmeal' },
{ 'obama' },
{ 'obeying' },
{ 'objections', 'objective', 'objectivity' },
{ 'obr' },
{ 'obscure' },
{ 'observation', 'observations', 'observed', 'observer', 'observes' },
{ 'obsession' },
{ 'obstacles' },
{ 'obtain' },
{ 'obtuse' },
{ 'obvious' },
{ 'obviously' },
{ 'occasions' },
{ 'occupation' },
{ 'occupying' },
{ 'occur', 'occurred' },
{ 'october' },
{ 'octogenarian' },
{ 'odds' },
{ 'off' },
{ 'offence' },
{ 'offense', 'offensive' },
{ 'offer', 'offered', 'offering' },
{ 'office', 'officer', 'officers' },
{ 'official', 'officially', 'officials' },
{ 'often' },
{ 'oh' },
{ 'oils' },
{ 'ointments' },
{ 'ok' },
{ 'okundaye' },
{ 'olaf' },
{ 'old' },
{ 'older' },
{ 'oliver' },
{ 'omitting' },
{ 'once' },
{ 'oncoming' },
{ 'one', 'ones' },
{ 'only' },
{ 'online' },
{ 'ontario' },
{ 'onto' },
{ 'op' },
{ 'open', 'opened' },
{ 'operate', 'operated', 'operations', 'operator' },
{ 'opinion' },
{ 'opponents' },
{ 'opportunities', 'opportunity' },
{ 'opportunists' },
{ 'opposed', 'opposes', 'opposing' },
{ 'opposite', 'opposition' },
{ 'oppression' },
{ 'optimism' },
{ 'option', 'optional', 'options' },
{ 'orangutans' },
{ 'orban' },
{ 'order', 'ordered', 'orders' },
{ 'ordination' },
{ 'ordinary' },
{ 'organization', 'organizations' },
{ 'organisation', 'organisations', 'organised', 'organiser' },
{ 'organizational' },
{ 'orientations' },
{ 'original', 'originally' },
{ 'orthodox' },
{ 'orthodoxy' },
{ 'ostracised' },
{ 'other', 'others' },
{ 'otherwise' },
{ 'ottawa' },
{ 'ouellet' },
{ 'our' },
{ 'ourselves' },
{ 'out' },
{ 'outbreak' },
{ 'outcome', 'outcomes' },
{ 'outer' },
{ 'outgoing' },
{ 'outlasted' },
{ 'outlined', 'outlines' },
{ 'outlook' },
{ 'output' },
{ 'outrage', 'outraged', 'outrageous' },
{ 'outrunning' },
{ 'outset' },
{ 'outside' },
{ 'outspoken' },
{ 'outweighs' },
{ 'over' },
{ 'overall' },
{ 'overcome' },
{ 'overlay' },
{ 'overlooked' },
{ 'overnight' },
{ 'overreach', 'overreaches' },
{ 'overrule' },
{ 'oversees' },
{ 'overseas' },
{ 'overshadowed' },
{ 'overweight' },
{ 'overwhelmed', 'overwhelming' },
{ 'overwhelmingly' },
{ 'overwrought' },
{ 'owe', 'owing' },
{ 'own', 'owned' },
{ 'owner' },
{ 'oxygen' },
{ 'ozturk' },
{ 'paapa' },
{ 'pack', 'packed' },
{ 'package', 'packaged' },
{ 'paddington' },
{ 'paediatrician' },
{ 'page', 'pages' },
{ 'paid' },
{ 'pain', 'painful' },
{ 'palates' },
{ 'pale' },
{ 'palestine' },
{ 'palestinian', 'palestinians' },
{ 'palpable' },
{ 'pam' },
{ 'pancrein' },
{ 'pandemic' },
{ 'pandemonium' },
{ 'panics' },
{ 'pants' },
{ 'pantone' },
{ 'papacy' },
{ 'paper' },
{ 'parable' },
{ 'parade' },
{ 'paradigm' },
{ 'parallel' },
{ 'paralysing' },
{ 'paralysis' },
{ 'paralyzing' },
{ 'parental', 'parents' },
{ 'pariahs' },
{ 'parliament', 'parliaments' },
{ 'parolin' },
{ 'parsons' },
{ 'part', 'parts' },
{ 'party' },
{ 'participants', 'participation' },
{ 'particular' },
{ 'particularly' },
{ 'partly' },
{ 'partners' },
{ 'partnerships' },
{ 'pass', 'passed', 'passing' },
{ 'passage' },
{ 'passion', 'passions' },
{ 'password' },
{ 'past', 'pasts' },
{ 'pastiche' },
{ 'pastoral' },
{ 'patented' },
{ 'path', 'paths' },
{ 'pathology' },
{ 'pathologist' },
{ 'pathways' },
{ 'patient', 'patients' },
{ 'pattern' },
{ 'paul' },
{ 'paula' },
{ 'paulescu' },
{ 'pause', 'pausing' },
{ 'pavia' },
{ 'pay', 'paying' },
{ 'payment' },
{ 'peace' },
{ 'peaks' },
{ 'pediatric' },
{ 'pedigree' },
{ 'peers' },
{ 'pegs' },
{ 'pen' },
{ 'penalized' },
{ 'penalties' },
{ 'pending' },
{ 'pendulum' },
{ 'penicillin' },
{ 'penicillium' },
{ 'pennsylvania' },
{ 'pentagon' },
{ 'penulis' },
{ 'people' },
{ 'per' },
{ 'perceive' },
{ 'percent' },
{ 'percentage' },
{ 'perception' },
{ 'percolated' },
{ 'perfect' },
{ 'perform', 'performance', 'performances', 'performed', 'performing' },
{ 'perhaps' },
{ 'perilous' },
{ 'period', 'periods' },
{ 'permanent' },
{ 'permission' },
{ 'permit', 'permitted' },
{ 'permutation', 'permutations' },
{ 'pernicious' },
{ 'perpetrated', 'perpetrators' },
{ 'persecution' },
{ 'persist' },
{ 'person', 'personal', 'personality', 'persons' },
{ 'perspective', 'perspectives' },
{ 'peru' },
{ 'pervasive' },
{ 'perverse', 'perversely' },
{ 'pete' },
{ 'peter' },
{ 'petri' },
{ 'pew' },
{ 'phang' },
{ 'pharmacist' },
{ 'phase' },
{ 'phd' },
{ 'phenomenon' },
{ 'philippines' },
{ 'philistine' },
{ 'philosopher', 'philosophical' },
{ 'philosophy' },
{ 'phone', 'phones' },
{ 'photo' },
{ 'photograph', 'photographed' },
{ 'physical' },
{ 'physician' },
{ 'physiology' },
{ 'physiologist' },
{ 'pick' },
{ 'pictures' },
{ 'piece' },
{ 'pietro' },
{ 'pill' },
{ 'pilloried' },
{ 'pinch' },
{ 'pipe' },
{ 'pistons' },
{ 'pitiful' },
{ 'pivot' },
{ 'place', 'placed', 'places', 'placing' },
{ 'plain' },
{ 'plan', 'plans' },
{ 'planet' },
{ 'plant', 'plants' },
{ 'plate', 'plates' },
{ 'platform' },
{ 'play', 'played', 'playing' },
{ 'playbook' },
{ 'players' },
{ 'playgrounds' },
{ 'pledge' },
{ 'plenty' },
{ 'plight' },
{ 'plms' },
{ 'plus' },
{ 'plummet' },
{ 'pluralism', 'plurality' },
{ 'poaceae' },
{ 'pocket' },
{ 'poem' },
{ 'point', 'pointed', 'pointing', 'points' },
{ 'pointless' },
{ 'poised' },
{ 'poison', 'poisoned' },
{ 'police' },
{ 'policies', 'policy' },
{ 'policymakers' },
{ 'political', 'politically', 'politics' },
{ 'politicians' },
{ 'politicisation' },
{ 'polling', 'polls' },
{ 'pollution' },
{ 'polytechnic' },
{ 'pontifical' },
{ 'pool' },
{ 'pop' },
{ 'pope', 'popes' },
{ 'population', 'populations' },
{ 'populace' },
{ 'popular' },
{ 'populist', 'populists' },
{ 'pornified' },
{ 'pornography' },
{ 'porridge', 'porridges' },
{ 'portion' },
{ 'portrayed' },
{ 'pose', 'posed' },
{ 'position', 'positive', 'positivity' },
{ 'possibility', 'possible', 'possibly' },
{ 'post', 'posted', 'posting' },
{ 'postdoctoral' },
{ 'poster' },
{ 'potential', 'potentially' },
{ 'potions' },
{ 'potter' },
{ 'potterheads' },
{ 'powell' },
{ 'power', 'powerful', 'powers' },
{ 'powerhouses' },
{ 'pr' },
{ 'practice', 'practices', 'practicing' },
{ 'pragmatism' },
{ 'precipitated' },
{ 'precise', 'precisely' },
{ 'predecessor' },
{ 'predict', 'predicted', 'predicting', 'prediction', 'predictions', 'predicts' },
{ 'predominantly' },
{ 'preface' },
{ 'prefect' },
{ 'preferences', 'preferred' },
{ 'pregnancy' },
{ 'pregnant' },
{ 'prejudice' },
{ 'prelate' },
{ 'premium' },
{ 'preparation', 'prepare', 'prepared', 'preparing' },
{ 'preparedness' },
{ 'preschool' },
{ 'prescribe' },
{ 'presence' },
{ 'present', 'presented', 'presenting', 'presents' },
{ 'preservatives' },
{ 'presidencies', 'presidency', 'president', 'presidents' },
{ 'presidential' },
{ 'press', 'pressing' },
{ 'pressure' },
{ 'presumably' },
{ 'pretend' },
{ 'pretense' },
{ 'pretty' },
{ 'prevail', 'prevailed', 'prevails' },
{ 'prevalent' },
{ 'preventable', 'prevented', 'prevention' },
{ 'previous' },
{ 'previously' },
{ 'prevost' },
{ 'price', 'prices', 'pricing' },
{ 'priests' },
{ 'primary' },
{ 'primate' },
{ 'prime' },
{ 'principal' },
{ 'principle', 'principles' },
{ 'prior' },
{ 'priorities', 'priority' },
{ 'prioritise' },
{ 'prison', 'prisons' },
{ 'privacy' },
{ 'private' },
{ 'privilege' },
{ 'prize' },
{ 'pro' },
{ 'probability', 'probable', 'probably' },
{ 'probiotics' },
{ 'problem', 'problems' },
{ 'procedure', 'procedures' },
{ 'process', 'processed', 'processing' },
{ 'processors' },
{ 'produce', 'produced', 'producers', 'producing' },
{ 'product', 'production', 'productive', 'products' },
{ 'prof' },
{ 'professional', 'professionals' },
{ 'professor', 'professors' },
{ 'proffered' },
{ 'profile', 'profiles' },
{ 'profit' },
{ 'profound' },
{ 'profoundly' },
{ 'program', 'programs' },
{ 'progress', 'progressive', 'progressives' },
{ 'prohibit', 'prohibition', 'prohibits' },
{ 'project' },
{ 'prolong' },
{ 'prominent' },
{ 'promise', 'promised', 'promises', 'promising' },
{ 'promote', 'promoting' },
{ 'prompted' },
{ 'pronouns' },
{ 'pronouncements' },
{ 'proof' },
{ 'propaganda' },
{ 'proper' },
{ 'properties' },
{ 'proponents' },
{ 'proportion' },
{ 'proposals', 'propose', 'proposed' },
{ 'proprietor' },
{ 'prosecuted' },
{ 'prospect' },
{ 'prosperity' },
{ 'protect', 'protected', 'protecting', 'protections' },
{ 'protein', 'proteins' },
{ 'protest', 'protestants', 'protested', 'protester', 'protesters', 'protests' },
{ 'proud' },
{ 'prove', 'proved' },
{ 'proven' },
{ 'provide', 'provided', 'providers', 'providing' },
{ 'provinces' },
{ 'provisions' },
{ 'provocation', 'provocative' },
{ 'psychiatry' },
{ 'psychological' },
{ 'psychologist', 'psychologists' },
{ 'psychopharmacological' },
{ 'pus' },
{ 'public' },
{ 'publicly' },
{ 'published', 'publishing' },
{ 'puffed' },
{ 'pulled', 'pulling' },
{ 'pulses' },
{ 'pumps' },
{ 'puncture' },
{ 'pundits' },
{ 'pups' },
{ 'puppies' },
{ 'purchases' },
{ 'pure' },
{ 'purge' },
{ 'purified' },
{ 'purity' },
{ 'purporting' },
{ 'purpose', 'purposes' },
{ 'pursue', 'pursued', 'pursuing' },
{ 'pursuer' },
{ 'push', 'pushed', 'pushing' },
{ 'pushback' },
{ 'put', 'putting' },
{ 'putin' },
{ 'puzzle' },
{ 'quackery' },
{ 'qualified' },
{ 'qualities' },
{ 'quantities' },
{ 'quantum' },
{ 'quarter', 'quarters' },
{ 'quebec' },
{ 'quest' },
{ 'question', 'questioning', 'questions' },
{ 'quick' },
{ 'quickly' },
{ 'quiet' },
{ 'quietly' },
{ 'quilting' },
{ 'quilter' },
{ 'quirrell' },
{ 'quite', 'quitting' },
{ 'quota' },
{ 'rabbit' },
{ 'race' },
{ 'rachel' },
{ 'racial' },
{ 'racist' },
{ 'radcliffe' },
{ 'radical' },
{ 'rafael' },
{ 'rafferty' },
{ 'raft' },
{ 'raging' },
{ 'raids' },
{ 'railed', 'railing' },
{ 'raise', 'raised', 'raising' },
{ 'rally', 'rallying' },
{ 'ramadan' },
{ 'ramping' },
{ 'rampant' },
{ 'ran' },
{ 'random' },
{ 'rang', 'range' },
{ 'rank' },
{ 'rant' },
{ 'rape' },
{ 'rapid' },
{ 'rapidly' },
{ 'rare', 'rarely' },
{ 'ratcheted' },
{ 'rate', 'rates', 'rating', 'ratings' },
{ 'rather' },
{ 'rational' },
{ 're' },
{ 'reach', 'reached' },
{ 'reaction' },
{ 'read', 'reading', 'reads' },
{ 'reader', 'readers' },
{ 'ready' },
{ 'reaffirm', 'reaffirmed' },
{ 'reagan', 'reaganism' },
{ 'real' },
{ 'realised', 'realises' },
{ 'realities', 'reality' },
{ 'realize', 'realizing' },
{ 'really' },
{ 'rearranged' },
{ 'rearview' },
{ 'reason', 'reasoning', 'reasons' },
{ 'reassess' },
{ 'rebecca' },
{ 'rebels' },
{ 'rebirth' },
{ 'rebuffed' },
{ 'rebuild' },
{ 'recall' },
{ 'receive', 'received', 'receives' },
{ 'recent', 'recently' },
{ 'receptors' },
{ 'recession' },
{ 'reciprocal' },
{ 'recognize', 'recognized' },
{ 'recognised' },
{ 'recommendations', 'recommended' },
{ 'reconcile' },
{ 'reconstruction' },
{ 'record', 'records' },
{ 'recover' },
{ 'recreate', 'recreating' },
{ 'recruited', 'recruitment' },
{ 'recycling' },
{ 'red', 'redding' },
{ 'redeeming' },
{ 'redefine', 'redefining' },
{ 'redirect', 'redirected' },
{ 'reduce', 'reduced', 'reduces', 'reducing' },
{ 'reduction', 'reductions' },
{ 'reelect' },
{ 'reengage' },
{ 'reeves' },
{ 'refashion' },
{ 'refer', 'reference' },
{ 'referendum' },
{ 'refine', 'refined' },
{ 'reflect', 'reflected', 'reflecting', 'reflects' },
{ 'reform', 'reformer' },
{ 'reformist' },
{ 'refrain' },
{ 'refusal', 'refuse', 'refused', 'refusing' },
{ 'regain' },
{ 'regard', 'regarded', 'regards' },
{ 'regardless' },
{ 'regent' },
{ 'regime' },
{ 'regimens' },
{ 'region', 'regions' },
{ 'registered' },
{ 'regulated', 'regulation', 'regulations' },
{ 'regular' },
{ 'rehiring' },
{ 'reins' },
{ 'reinhard' },
{ 'reinstated' },
{ 'reiterated' },
{ 'reject', 'rejected' },
{ 'relative', 'relatively' },
{ 'related', 'relations' },
{ 'relationship', 'relationships' },
{ 'release', 'released' },
{ 'relentless' },
{ 'relevant' },
{ 'relies', 'rely' },
{ 'reliability' },
{ 'relic' },
{ 'religious' },
{ 'religion' },
{ 'remain', 'remained', 'remains' },
{ 'remake' },
{ 'remarkable', 'remarks' },
{ 'remedied' },
{ 'remember', 'remembered', 'remembering' },
{ 'remind', 'reminded', 'reminder' },
{ 'remotely' },
{ 'removals', 'remove', 'removed' },
{ 'rendering' },
{ 'reneging' },
{ 'renew', 'renewable', 'renewables' },
{ 'reorganisation' },
{ 'repeated' },
{ 'repeatedly' },
{ 'repertoire' },
{ 'repetition' },
{ 'replace', 'replaced', 'replacing' },
{ 'replied', 'replies' },
{ 'report', 'reported', 'reporters', 'reporting', 'reports' },
{ 'reportedly' },
{ 'reposted' },
{ 'represent', 'representative', 'representatives', 'represented', 'represents' },
{ 'representation' },
{ 'reprieve' },
{ 'reproductive' },
{ 'republic' },
{ 'republican', 'republicans' },
{ 'repudiated' },
{ 'repurposed' },
{ 'reputation' },
{ 'request', 'requested', 'requests' },
{ 'require', 'required', 'requirements' },
{ 'rescinded' },
{ 'research', 'researcher', 'researchers' },
{ 'resentment' },
{ 'reserve', 'reserved' },
{ 'reshuffle' },
{ 'residences', 'resident', 'residents' },
{ 'residential' },
{ 'resign', 'resignation', 'resigned' },
{ 'resilience' },
{ 'resolution' },
{ 'resolve', 'resolved' },
{ 'resonance', 'resonate' },
{ 'resort' },
{ 'resounding' },
{ 'resources' },
{ 'respect' },
{ 'respirator' },
{ 'respiratory' },
{ 'respond', 'responded', 'respondents', 'responding' },
{ 'response', 'responsibility', 'responsible' },
{ 'rest' },
{ 'restaurants' },
{ 'restore', 'restored', 'restoring' },
{ 'restraints' },
{ 'restricted', 'restricting', 'restrictions', 'restrictive', 'restricts' },
{ 'result', 'resulted', 'resulting', 'results' },
{ 'resurfaced' },
{ 'resurrect', 'resurrected' },
{ 'retention' },
{ 'rethink' },
{ 'rethought' },
{ 'retiring' },
{ 'retreat' },
{ 'return', 'returned', 'returning' },
{ 'reuters' },
{ 'reveal' },
{ 'revenge' },
{ 'revenue' },
{ 'reversals', 'reverse', 'reversed' },
{ 'review' },
{ 'reviled' },
{ 'revised', 'revision', 'revisions' },
{ 'revisiting' },
{ 'revive', 'revived', 'reviving' },
{ 'revocations' },
{ 'revoke', 'revoked' },
{ 'revolutionized' },
{ 'revolving' },
{ 'revulsion' },
{ 'reward' },
{ 'rewatch' },
{ 'rfk' },
{ 'rhapsody' },
{ 'rhetoric', 'rhetorical' },
{ 'rhythm' },
{ 'ri' },
{ 'riccardo' },
{ 'rice' },
{ 'rich' },
{ 'richard' },
{ 'richer' },
{ 'rickman' },
{ 'riding' },
{ 'ridiculous' },
{ 'right', 'rights' },
{ 'rightly' },
{ 'rightwing' },
{ 'rilis' },
{ 'ringfenced' },
{ 'ringleader' },
{ 'rise', 'rising' },
{ 'risen' },
{ 'rishi' },
{ 'risk', 'risking' },
{ 'rite', 'rites' },
{ 'rival', 'rivals' },
{ 'river' },
{ 'road' },
{ 'roaring' },
{ 'robbie' },
{ 'robert' },
{ 'robin' },
{ 'robots' },
{ 'robust' },
{ 'rocking' },
{ 'rocket', 'rockets' },
{ 'roland' },
{ 'role', 'roles' },
{ 'roll', 'rolled' },
{ 'rollers' },
{ 'roman' },
{ 'romanian' },
{ 'ron' },
{ 'ronald' },
{ 'room', 'rooms' },
{ 'root', 'rooted' },
{ 'rose' },
{ 'roth' },
{ 'roughly' },
{ 'round' },
{ 'route' },
{ 'roy' },
{ 'rr' },
{ 'rubella' },
{ 'rubio' },
{ 'rug' },
{ 'rule', 'ruled', 'ruling' },
{ 'rumeysa' },
{ 'rumours' },
{ 'run', 'running', 'runs' },
{ 'runcorn' },
{ 'rupert' },
{ 'rural' },
{ 'russia' },
{ 'russian' },
{ 'ryan' },
{ 's' },
{ 'sack', 'sacked' },
{ 'sacrificing' },
{ 'sad' },
{ 'sadiq' },
{ 'sadly' },
{ 'safe', 'safely' },
{ 'safeguards' },
{ 'safer' },
{ 'safety' },
{ 'saga' },
{ 'said' },
{ 'sake' },
{ 'sales' },
{ 'salient' },
{ 'saliva' },
{ 'salling' },
{ 'sallow' },
{ 'salt' },
{ 'salvador' },
{ 'salvadoran' },
{ 'salvarsan' },
{ 'salvation' },
{ 'same' },
{ 'samples' },
{ 'samsung' },
{ 'samuel' },
{ 'sanatarium' },
{ 'sanction' },
{ 'sanger' },
{ 'sanity' },
{ 'sanitise' },
{ 'sarah' },
{ 'sasha' },
{ 'satisfying' },
{ 'saturday' },
{ 'saudi' },
{ 'sauntered' },
{ 'save', 'saved', 'saving' },
{ 'saw' },
{ 'sawmills' },
{ 'say', 'saying', 'says' },
{ 'scale', 'scales' },
{ 'scam', 'scams' },
{ 'scammers' },
{ 'scan' },
{ 'scandal', 'scandalous' },
{ 'scars' },
{ 'scared' },
{ 'scaremongering' },
{ 'scattered' },
{ 'scenario', 'scenarios' },
{ 'sceptical', 'scepticism' },
{ 'scheme', 'scheming' },
{ 'schneemann' },
{ 'scholar' },
{ 'scholarly' },
{ 'scholarship' },
{ 'scholz' },
{ 'school', 'schools' },
{ 'schoolchildren' },
{ 'schoolwork' },
{ 'science', 'sciences' },
{ 'scientific' },
{ 'scientist', 'scientists' },
{ 'scientology' },
{ 'scientologists' },
{ 'scola' },
{ 'scooping' },
{ 'scotia' },
{ 'scotland' },
{ 'scottish' },
{ 'scourge' },
{ 'scrap' },
{ 'scratch' },
{ 'screen' },
{ 'scroll' },
{ 'scrutiny' },
{ 'seales' },
{ 'search', 'searched' },
{ 'season' },
{ 'seat', 'seating', 'seats' },
{ 'second', 'seconds' },
{ 'secondary' },
{ 'secret' },
{ 'secretary' },
{ 'section' },
{ 'sector' },
{ 'secure', 'secured', 'securities', 'security' },
{ 'see', 'seeing', 'sees' },
{ 'seeds' },
{ 'seek', 'seeks' },
{ 'seem', 'seemed', 'seems' },
{ 'seen' },
{ 'seethe' },
{ 'segment' },
{ 'select', 'selected', 'selecting', 'selection' },
{ 'sell', 'selling', 'sells' },
{ 'seller' },
{ 'semblance' },
{ 'semiconductors' },
{ 'senadeera' },
{ 'senate', 'senator', 'senators' },
{ 'send', 'sending' },
{ 'senior' },
{ 'sense', 'sensing' },
{ 'sensational' },
{ 'sensationalised' },
{ 'senseless' },
{ 'sensitivity' },
{ 'sent' },
{ 'sentiment' },
{ 'september' },
{ 'sequel' },
{ 'sequence' },
{ 'serendipity' },
{ 'series' },
{ 'serious' },
{ 'seriously' },
{ 'serum' },
{ 'serve', 'served', 'serves', 'serving' },
{ 'service', 'services' },
{ 'set', 'sets', 'setting', 'settings' },
{ 'setback' },
{ 'settle', 'settled' },
{ 'seven' },
{ 'seventh' },
{ 'seventies' },
{ 'several', 'severe', 'severed', 'severely' },
{ 'severus' },
{ 'sex' },
{ 'sexual' },
{ 'shadow' },
{ 'shake', 'shaking' },
{ 'shaken' },
{ 'shallow' },
{ 'shaped', 'shapes' },
{ 'shapiro' },
{ 'share', 'shared', 'shares' },
{ 'sharp' },
{ 'sharpening' },
{ 'sharply' },
{ 'shatter', 'shattered' },
{ 'shelves' },
{ 'shields' },
{ 'shift', 'shifted', 'shifts' },
{ 'shipped', 'shipping' },
{ 'shipment', 'shipments' },
{ 'shocking', 'shocks' },
{ 'shoes' },
{ 'shootings' },
{ 'shooters' },
{ 'shop', 'shopping' },
{ 'shoppers' },
{ 'short' },
{ 'shortages' },
{ 'shortest' },
{ 'shortly' },
{ 'shouldn' },
{ 'shout' },
{ 'show', 'showed', 'shows' },
{ 'showdown' },
{ 'shown' },
{ 'shrewd' },
{ 'shrier' },
{ 'shrilly' },
{ 'shunting' },
{ 'shut' },
{ 'shweder' },
{ 'siblings' },
{ 'sick' },
{ 'side', 'sides' },
{ 'sideline' },
{ 'sign', 'signed', 'signs' },
{ 'signal', 'signaled' },
{ 'signature' },
{ 'significance', 'significant' },
{ 'significantly' },
{ 'silencing' },
{ 'silos' },
{ 'silver' },
{ 'similar' },
{ 'similarly' },
{ 'simpler' },
{ 'simply' },
{ 'simplistic' },
{ 'simultaneously' },
{ 'since' },
{ 'single' },
{ 'singular' },
{ 'sir' },
{ 'sistine' },
{ 'sit' },
{ 'site' },
{ 'situation' },
{ 'six' },
{ 'sixties' },
{ 'sizes' },
{ 'skeptical' },
{ 'sketchy' },
{ 'skewed' },
{ 'skill', 'skills' },
{ 'skin' },
{ 'skirts' },
{ 'skovlunde' },
{ 'skyrocket', 'skyrocketing' },
{ 'slammed' },
{ 'slap' },
{ 'slashed', 'slashing' },
{ 'slated' },
{ 'slaughterhouses' },
{ 'sleep', 'sleeping' },
{ 'sleepwalking' },
{ 'slide' },
{ 'slight' },
{ 'sliver' },
{ 'slop' },
{ 'sloppiest' },
{ 'slow', 'slows' },
{ 'slowdown' },
{ 'slower' },
{ 'slurs' },
{ 'small' },
{ 'smallest' },
{ 'smart' },
{ 'smartphone', 'smartphones' },
{ 'smear' },
{ 'snacking', 'snacks' },
{ 'snape' },
{ 'snow' },
{ 'snowballing' },
{ 'so', 'sos' },
{ 'sociable' },
{ 'social', 'socially' },
{ 'societal' },
{ 'societies', 'society' },
{ 'sociologists' },
{ 'sociopath' },
{ 'socrates' },
{ 'sodha' },
{ 'softly' },
{ 'solace' },
{ 'solely' },
{ 'solemnity' },
{ 'solution', 'solutions' },
{ 'solve', 'solved' },
{ 'some' },
{ 'somehow' },
{ 'someone' },
{ 'something' },
{ 'sometimes' },
{ 'somewhat' },
{ 'son', 'sons' },
{ 'sonia' },
{ 'soon' },
{ 'sooner' },
{ 'soothing' },
{ 'sophia' },
{ 'sort', 'sorts' },
{ 'sought' },
{ 'soul' },
{ 'sound' },
{ 'source', 'sources' },
{ 'south' },
{ 'southern' },
{ 'space', 'spaces' },
{ 'spacious' },
{ 'spain' },
{ 'spare' },
{ 'sparked' },
{ 'spawned' },
{ 'speaking' },
{ 'species' },
{ 'special', 'specializes' },
{ 'specialist' },
{ 'specific', 'specifically' },
{ 'spectacular' },
{ 'spectrum' },
{ 'speculation' },
{ 'speech' },
{ 'speed' },
{ 'spend', 'spending' },
{ 'spent' },
{ 'spewing' },
{ 'sphere' },
{ 'spice' },
{ 'spike', 'spikes' },
{ 'spine' },
{ 'spirited', 'spirits' },
{ 'spirochete' },
{ 'spoke' },
{ 'spoken' },
{ 'spokesperson' },
{ 'spooked' },
{ 'spore', 'spores' },
{ 'sport', 'sports' },
{ 'spread', 'spreading' },
{ 'spreadsheets' },
{ 'spring' },
{ 'square' },
{ 'stability', 'stabilizing' },
{ 'stable' },
{ 'staff' },
{ 'stage', 'staged', 'stages' },
{ 'staggering' },
{ 'stairwell' },
{ 'stalling', 'stalls' },
{ 'stamp' },
{ 'stance' },
{ 'stand', 'standing', 'stands' },
{ 'standard', 'standards' },
{ 'standoff' },
{ 'staphylococcus' },
{ 'star' },
{ 'starch' },
{ 'starker' },
{ 'starmer' },
{ 'start', 'started', 'starting', 'starts' },
{ 'stash' },
{ 'state', 'states', 'stating' },
{ 'statement', 'statements' },
{ 'statistic', 'statistics' },
{ 'status' },
{ 'statuses' },
{ 'stay', 'staying' },
{ 'steadily' },
{ 'steal' },
{ 'steel' },
{ 'stepped', 'steps' },
{ 'stepbrother' },
{ 'stephen' },
{ 'stepson' },
{ 'stereotyped', 'stereotypes' },
{ 'sterilize', 'sterilizing' },
{ 'steve' },
{ 'stew' },
{ 'stick' },
{ 'stickiness' },
{ 'stiffer' },
{ 'still' },
{ 'stirring' },
{ 'stock', 'stocking' },
{ 'stoked' },
{ 'stone' },
{ 'stonewall' },
{ 'stood' },
{ 'stop', 'stopped' },
{ 'store', 'stores' },
{ 'stories', 'story' },
{ 'storm' },
{ 'storytelling' },
{ 'straight' },
{ 'strains' },
{ 'strand' },
{ 'strange', 'strangely' },
{ 'strangle' },
{ 'stranglehold' },
{ 'strategies', 'strategy' },
{ 'straw' },
{ 'stream', 'streaming', 'streams' },
{ 'street', 'streets' },
{ 'strength' },
{ 'strengthened', 'strengthening' },
{ 'stress', 'stressed', 'stresses' },
{ 'strictly' },
{ 'stride', 'strides' },
{ 'strikes', 'striking' },
{ 'string' },
{ 'stringent' },
{ 'stripped' },
{ 'strived' },
{ 'stroke' },
{ 'strong' },
{ 'stronger' },
{ 'strongly' },
{ 'struck' },
{ 'structurally', 'structure', 'structured', 'structures' },
{ 'struggle', 'struggled', 'struggling' },
{ 'strung' },
{ 'stuart' },
{ 'student', 'students' },
{ 'studied', 'studies', 'study' },
{ 'studio' },
{ 'stuff' },
{ 'stunning' },
{ 'style' },
{ 'sued' },
{ 'sub' },
{ 'subconscious' },
{ 'subculture' },
{ 'subject', 'subjective' },
{ 'subliminal' },
{ 'submission', 'submissive' },
{ 'subscriptions' },
{ 'subsequent', 'subsequently' },
{ 'subsidies' },
{ 'substance', 'substances' },
{ 'substantial' },
{ 'substitute', 'substituting' },
{ 'suburb', 'suburbs' },
{ 'subverted' },
{ 'succeed', 'succeeded' },
{ 'success', 'successful', 'successfully', 'succession' },
{ 'successor' },
{ 'succumbed' },
{ 'such' },
{ 'sudan' },
{ 'sudden' },
{ 'suddenly' },
{ 'sufferers', 'suffering' },
{ 'suffice' },
{ 'sufficient' },
{ 'suffocated', 'suffocating' },
{ 'sugar', 'sugars' },
{ 'sugary' },
{ 'suggest', 'suggested', 'suggesting', 'suggestions', 'suggests' },
{ 'sui' },
{ 'suicidal', 'suicide', 'suicides' },
{ 'suit', 'suited' },
{ 'sumber' },
{ 'summer' },
{ 'summit' },
{ 'summons' },
{ 'sumption' },
{ 'sunak' },
{ 'sunday' },
{ 'sundry' },
{ 'sunglasses' },
{ 'superfan' },
{ 'superintendent' },
{ 'supermarket' },
{ 'superpermutation', 'superpermutations' },
{ 'superstitions' },
{ 'supplement', 'supplements' },
{ 'supply' },
{ 'supplicant' },
{ 'suppliers' },
{ 'support', 'supported', 'supporters', 'supporting' },
{ 'supposed' },
{ 'supposedly' },
{ 'supreme' },
{ 'supremacy' },
{ 'supremacist' },
{ 'sure', 'surely' },
{ 'surface' },
{ 'surge' },
{ 'surgeon' },
{ 'suri' },
{ 'surprise', 'surprising' },
{ 'surrendering' },
{ 'surrounding' },
{ 'surveillance' },
{ 'survey', 'surveys' },
{ 'survival', 'survive', 'surviving' },
{ 'suspected', 'suspects' },
{ 'suspended' },
{ 'suspicious' },
{ 'suspicion' },
{ 'suss' },
{ 'sustain', 'sustainable', 'sustained' },
{ 'suzumiya' },
{ 'swagger' },
{ 'swallowed' },
{ 'swapping' },
{ 'swathes' },
{ 'sweden' },
{ 'sweetened', 'sweeteners' },
{ 'swell' },
{ 'swift' },
{ 'swiftly' },
{ 'swing', 'swinging' },
{ 'swirl' },
{ 'switching' },
{ 'symbol', 'symbols' },
{ 'sympathy' },
{ 'symptoms' },
{ 'synagogues' },
{ 'synonymous' },
{ 'synthesized' },
{ 'synthesis' },
{ 'syphilis' },
{ 'system', 'systemic', 'systems' },
{ 'systematically' },
{ 'søren' },
{ 't' },
{ 'table' },
{ 'taboo' },
{ 'tacit' },
{ 'tacitly' },
{ 'tackling' },
{ 'tactics' },
{ 'tag' },
{ 'tagle' },
{ 'taint' },
{ 'take', 'takes', 'taking' },
{ 'taken' },
{ 'tale' },
{ 'talent', 'talents' },
{ 'talk', 'talked' },
{ 'tall' },
{ 'tame' },
{ 'tanggal' },
{ 'tantamount' },
{ 'taped' },
{ 'target', 'targeted', 'targeting', 'targets' },
{ 'tariff', 'tariffs' },
{ 'task', 'tasks' },
{ 'taster' },
{ 'taught' },
{ 'tax', 'taxed', 'taxes' },
{ 'taxpayer' },
{ 'teach', 'teaching' },
{ 'teacher' },
{ 'team' },
{ 'tears' },
{ 'teasing' },
{ 'tech' },
{ 'techinsights' },
{ 'technically' },
{ 'technicians' },
{ 'technological', 'technology' },
{ 'teens' },
{ 'teenage', 'teenaged', 'teenagers' },
{ 'teeth' },
{ 'telegraph' },
{ 'tell', 'telling', 'tells' },
{ 'tellingly' },
{ 'temperature', 'temperatures' },
{ 'template' },
{ 'temporarily' },
{ 'tempt' },
{ 'temptation' },
{ 'tens' },
{ 'tend', 'tends' },
{ 'tendencies' },
{ 'tensions' },
{ 'tenure' },
{ 'terbit' },
{ 'term', 'terms' },
{ 'terminating' },
{ 'terminology' },
{ 'terrible' },
{ 'terrified', 'terrifying' },
{ 'territory' },
{ 'terror', 'terrorize' },
{ 'terrorist', 'terrorists' },
{ 'tersebut' },
{ 'tesla' },
{ 'test', 'tested', 'tests' },
{ 'texas' },
{ 'text' },
{ 'texture' },
{ 'than' },
{ 'thank', 'thankfully', 'thanks' },
{ 'theater' },
{ 'theme', 'themes' },
{ 'themselves' },
{ 'then' },
{ 'theocrats' },
{ 'theories', 'theory' },
{ 'therapeutic' },
{ 'therapy' },
{ 'therapist', 'therapists' },
{ 'there' },
{ 'thereafter' },
{ 'thereby' },
{ 'therefore' },
{ 'theresa' },
{ 'thin', 'thinning' },
{ 'thing', 'things' },
{ 'think', 'thinking', 'thinks' },
{ 'thinker', 'thinkers' },
{ 'third' },
{ 'thirty' },
{ 'thomas' },
{ 'thorazine' },
{ 'thoroughly' },
{ 'though' },
{ 'thought', 'thoughts' },
{ 'thousand', 'thousands' },
{ 'threadbare' },
{ 'threat', 'threats' },
{ 'threaten', 'threatened', 'threatening', 'threatens' },
{ 'three' },
{ 'threshold' },
{ 'thrive', 'thriving' },
{ 'thrones' },
{ 'through' },
{ 'throughout' },
{ 'throwback' },
{ 'thursday' },
{ 'thylacine' },
{ 'ti' },
{ 'tiberias' },
{ 'ticking' },
{ 'tickling' },
{ 'tide' },
{ 'ties' },
{ 'tighter' },
{ 'time', 'times', 'timing' },
{ 'timeframe' },
{ 'timelines' },
{ 'timetable' },
{ 'tiny' },
{ 'tired' },
{ 'toasted' },
{ 'today' },
{ 'todd' },
{ 'together' },
{ 'toilet' },
{ 'told' },
{ 'toll' },
{ 'tom' },
{ 'tomorrow' },
{ 'tongue' },
{ 'too' },
{ 'took' },
{ 'top' },
{ 'topical' },
{ 'tories', 'tory' },
{ 'torment' },
{ 'torrent' },
{ 'tortoise' },
{ 'total', 'totally' },
{ 'touch' },
{ 'touchy' },
{ 'tour' },
{ 'tourists' },
{ 'toward', 'towards' },
{ 'toxic', 'toxicity' },
{ 'toxin', 'toxins' },
{ 'toys' },
{ 'trace' },
{ 'track' },
{ 'tracker' },
{ 'trad' },
{ 'trade', 'trading' },
{ 'trader' },
{ 'tradition', 'traditional', 'traditionally', 'traditions' },
{ 'traditionalist' },
{ 'traffic' },
{ 'trafficking' },
{ 'tragedy' },
{ 'tragic' },
{ 'trail' },
{ 'train', 'trained', 'training' },
{ 'trait', 'traits' },
{ 'trajectory' },
{ 'trans' },
{ 'tranquilizer' },
{ 'transcends' },
{ 'transcriptase' },
{ 'transfer' },
{ 'transform', 'transforms' },
{ 'transgender' },
{ 'transition', 'transitions' },
{ 'translated' },
{ 'transparency' },
{ 'transphobic' },
{ 'trauma', 'traumas' },
{ 'traumatising' },
{ 'travel', 'travelers', 'travelling' },
{ 'travesty' },
{ 'treasure' },
{ 'treasury' },
{ 'treat', 'treated', 'treating' },
{ 'treatment' },
{ 'trebled' },
{ 'trees' },
{ 'tremendous' },
{ 'trend', 'trends' },
{ 'tried', 'try', 'trying' },
{ 'trial', 'trials' },
{ 'tribes' },
{ 'tributes' },
{ 'tricking' },
{ 'tricky' },
{ 'trigger', 'triggered' },
{ 'trillions' },
{ 'trimmed' },
{ 'tripped' },
{ 'triumph' },
{ 'triumphant' },
{ 'trivialisation' },
{ 'troubling' },
{ 'true' },
{ 'truly' },
{ 'trump' },
{ 'trumpism' },
{ 'trumpist' },
{ 'trust', 'trusted', 'trusts' },
{ 'truth', 'truths' },
{ 'tube' },
{ 'tuesday' },
{ 'tufts' },
{ 'tulips' },
{ 'tunnels' },
{ 'turbines' },
{ 'turkson' },
{ 'turn', 'turned', 'turning', 'turns' },
{ 'tv' },
{ 'tweet', 'tweeted' },
{ 'twenty' },
{ 'twice' },
{ 'twist' },
{ 'two' },
{ 'type', 'types' },
{ 'typical', 'typically' },
{ 'tyranny' },
{ 'ubs' },
{ 'ubiquitous' },
{ 'uk' },
{ 'ukraine' },
{ 'ultimate', 'ultimately' },
{ 'ultra' },
{ 'un' },
{ 'unable' },
{ 'unacceptable' },
{ 'unafraid' },
{ 'unanimous' },
{ 'unannounced' },
{ 'unapologetic' },
{ 'unappreciated' },
{ 'unblock' },
{ 'uncanny' },
{ 'uncertain' },
{ 'uncertainty' },
{ 'unchanged' },
{ 'unclear' },
{ 'unconventional' },
{ 'under' },
{ 'underage' },
{ 'undercuts' },
{ 'undergo' },
{ 'undergone' },
{ 'underlying' },
{ 'undermine', 'undermined', 'undermining' },
{ 'underpin' },
{ 'understand', 'understandably', 'understanding', 'understands' },
{ 'understood' },
{ 'undo' },
{ 'undocumented' },
{ 'unease' },
{ 'unemployment' },
{ 'unexpectedly' },
{ 'unfairly' },
{ 'unfavourable' },
{ 'unfettered' },
{ 'unfinished' },
{ 'unfolding', 'unfolds' },
{ 'unfortunately' },
{ 'unfulfilled' },
{ 'unhealed' },
{ 'unhealthy' },
{ 'unheard' },
{ 'unhinged' },
{ 'unified' },
{ 'uniformed' },
{ 'unintentionally' },
{ 'union', 'unions' },
{ 'unique' },
{ 'unisex' },
{ 'unison' },
{ 'united' },
{ 'universally', 'universities', 'university' },
{ 'unknown' },
{ 'unlawful' },
{ 'unlike', 'unlikely' },
{ 'unlivable' },
{ 'unlock', 'unlocked' },
{ 'unmarked' },
{ 'unnecessary' },
{ 'unpleasant' },
{ 'unprecedented' },
{ 'unpredictability', 'unpredictable' },
{ 'unreal' },
{ 'unsafe' },
{ 'unsteady' },
{ 'unsuccessful' },
{ 'unsure' },
{ 'untangle' },
{ 'until' },
{ 'unusual' },
{ 'unveiled' },
{ 'unwary' },
{ 'up' },
{ 'upbringing' },
{ 'updated' },
{ 'upend' },
{ 'upf' },
{ 'upfront' },
{ 'upgraded' },
{ 'upon' },
{ 'upper' },
{ 'upset', 'upsetting' },
{ 'upside' },
{ 'urged', 'urging' },
{ 'urgency' },
{ 'usaid' },
{ 'use', 'used', 'useful', 'uses', 'using' },
{ 'useless' },
{ 'user', 'users' },
{ 'username' },
{ 'usher' },
{ 'usually' },
{ 'utilising' },
{ 'uxbridge' },
{ 'vacation' },
{ 'vaccinations', 'vaccine', 'vaccines' },
{ 'valid', 'validation' },
{ 'value', 'values' },
{ 'van' },
{ 'vance' },
{ 'vantage' },
{ 'vapors' },
{ 'varied', 'vary', 'varying' },
{ 'variation' },
{ 'variety' },
{ 'various' },
{ 'vast' },
{ 'vatican' },
{ 've' },
{ 'veered' },
{ 'vegan' },
{ 'vegetables' },
{ 'vegetarian' },
{ 'vehicle' },
{ 'veracity' },
{ 'verbal' },
{ 'verge' },
{ 'very' },
{ 'verification' },
{ 'verify' },
{ 'verisimilitude' },
{ 'vermont' },
{ 'veronica' },
{ 'versions' },
{ 'vertically' },
{ 'vetting' },
{ 'veteran' },
{ 'via' },
{ 'vibrating' },
{ 'vice' },
{ 'victim', 'victimization', 'victims' },
{ 'victorious', 'victory' },
{ 'video', 'videos' },
{ 'vietnam' },
{ 'view', 'viewed', 'views' },
{ 'viewer' },
{ 'viewpoint', 'viewpoints' },
{ 'vigil' },
{ 'viktor' },
{ 'villainy' },
{ 'violate', 'violating', 'violation', 'violations' },
{ 'violence' },
{ 'violent', 'violently' },
{ 'virginia' },
{ 'virtual', 'virtually' },
{ 'virus' },
{ 'visa', 'visas' },
{ 'visaholders' },
{ 'vision' },
{ 'visit', 'visited', 'visiting', 'visits' },
{ 'visual' },
{ 'vital' },
{ 'vitamin', 'vitamins' },
{ 'vladimir' },
{ 'voice', 'voices' },
{ 'volatile' },
{ 'volume' },
{ 'volunteers' },
{ 'voluntary' },
{ 'vormals' },
{ 'vote', 'voted', 'voting' },
{ 'voters' },
{ 'vow', 'vows' },
{ 'vulnerability', 'vulnerable' },
{ 'w' },
{ 'wa' },
{ 'wage' },
{ 'wait', 'waiting' },
{ 'wakefield' },
{ 'waktu' },
{ 'walk', 'walked', 'walking' },
{ 'wall' },
{ 'walter' },
{ 'wander' },
{ 'want', 'wanted', 'wanting', 'wants' },
{ 'war', 'wars' },
{ 'ward' },
{ 'warfare' },
{ 'wary' },
{ 'warn', 'warned', 'warnings', 'warns' },
{ 'warner' },
{ 'warp' },
{ 'washing' },
{ 'washington' },
{ 'wasn' },
{ 'watch', 'watched', 'watching' },
{ 'water', 'waters' },
{ 'wave' },
{ 'way', 'ways' },
{ 'weak' },
{ 'weaken', 'weakened', 'weakening' },
{ 'weaker' },
{ 'wealth' },
{ 'wealthy' },
{ 'wealthiest' },
{ 'weapon', 'weaponize', 'weapons' },
{ 'wearing' },
{ 'weasley' },
{ 'weather' },
{ 'weber' },
{ 'wed', 'wedding' },
{ 'wedbush' },
{ 'wednesday' },
{ 'week', 'weeks' },
{ 'weekend' },
{ 'weekly' },
{ 'weird' },
{ 'welcome' },
{ 'welfare' },
{ 'well', 'wellness' },
{ 'went' },
{ 'wesleyan' },
{ 'western' },
{ 'westminster' },
{ 'whales' },
{ 'what' },
{ 'whatever' },
{ 'whatsapp' },
{ 'wheat' },
{ 'when' },
{ 'where' },
{ 'whereas' },
{ 'whether' },
{ 'why' },
{ 'which' },
{ 'whilst' },
{ 'whim' },
{ 'white', 'whiteness' },
{ 'whiter' },
{ 'who' },
{ 'whole' },
{ 'whom' },
{ 'whose' },
{ 'wide', 'widely' },
{ 'wider' },
{ 'widespread' },
{ 'wife' },
{ 'wiki' },
{ 'wild' },
{ 'wilhelm' },
{ 'wilkinson' },
{ 'willful', 'willing' },
{ 'williams' },
{ 'win', 'winning', 'wins' },
{ 'wind' },
{ 'window', 'windows' },
{ 'wine' },
{ 'wipe', 'wiped' },
{ 'wise' },
{ 'wish' },
{ 'withheld' },
{ 'within' },
{ 'without' },
{ 'wo' },
{ 'woes' },
{ 'woke' },
{ 'wolf' },
{ 'wolves' },
{ 'woman' },
{ 'women' },
{ 'won' },
{ 'wonder', 'wondered', 'wondering' },
{ 'word', 'words' },
{ 'work', 'worked', 'working' },
{ 'worker', 'workers' },
{ 'workforce' },
{ 'workplaces' },
{ 'world', 'worlds' },
{ 'worn' },
{ 'worried', 'worries', 'worry', 'worrying' },
{ 'worse' },
{ 'worsened' },
{ 'worship' },
{ 'worst' },
{ 'worth' },
{ 'worthier' },
{ 'wouldn' },
{ 'wounds' },
{ 'wrecking' },
{ 'wright' },
{ 'write', 'writing', 'writings' },
{ 'writer', 'writers' },
{ 'written' },
{ 'wrong' },
{ 'wrongly' },
{ 'wrote' },
{ 'x' },
{ 'xi' },
{ 'xinis' },
{ 'yardsticks' },
{ 'yes' },
{ 'year', 'years' },
{ 'yearning' },
{ 'yemen' },
{ 'yesterday' },
{ 'yet' },
{ 'yielding' },
{ 'yoghurt' },
{ 'yogurts' },
{ 'york' },
{ 'young' },
{ 'youngest' },
{ 'yourself' },
{ 'youth' },
{ 'youtube' },
{ 'z' },
{ 'zachary' },
{ 'zealous' },
{ 'zedong' },
{ 'zelenskyy' },
{ 'zero' },
{ 'zidovudine' },
{ 'zionism' },
{ 'zone', 'zones' },
{ 'zoo', 'zoos' },
{ 'zoom' },

]

all_words = set(itertools.chain.from_iterable(semantic_classes))

stem_to_words = defaultdict(set)
word_to_stem = {}
for word in all_words:
    stem = porter_stem(word)
    stem_to_words[stem].add(word)
    word_to_stem[word] = stem

understems = 0
true_pairs = 0
total_pairs = 0

for cls in semantic_classes:
    cls_list = list(cls)
    for i in range(len(cls_list)):
        for j in range(i + 1, len(cls_list)):
            w1, w2 = cls_list[i], cls_list[j]
            total_pairs += 1
            if word_to_stem[w1] == word_to_stem[w2]:
                true_pairs += 1
            else:
                understems += 1

overstems = 0
checked_pairs = set()
for stem, words in stem_to_words.items():
    word_list = list(words)
    for i in range(len(word_list)):
        for j in range(i + 1, len(word_list)):
            w1, w2 = word_list[i], word_list[j]
            cls1 = next(i for i, cls in enumerate(semantic_classes) if w1 in cls)
            cls2 = next(i for i, cls in enumerate(semantic_classes) if w2 in cls)
            if cls1 != cls2 and (w1, w2) not in checked_pairs:
                overstems += 1
                checked_pairs.add((w1, w2))
                checked_pairs.add((w2, w1))

total_words = len(all_words)
total_stems = len(stem_to_words)
mean_conflation = total_words / total_stems

print(f"Total Pairs (within classes): {total_pairs}")
print(f"Correctly conflated pairs: {true_pairs}")
print(f"Understemming Index (UI): {understems / total_pairs:.2f}")
print(f"Overstemming Index (OI): {overstems / total_pairs:.2f}")
print(f"Mean Word Conflation (MWC): {mean_conflation:.2f}")
